# Generated by Django 5.1.15 on 2026-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_temporarydutypermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermission",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
