# Generated by Django 5.1.15 on 2026-06-21 16:58

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


def _seed_default_settings(apps, schema_editor):
    # Materialise the singleton at migrate time so the settings row exists at
    # rest (no write on the selector read path; replica-safe).
    model = apps.get_model("ops_submissions", "SubmissionControlSettings")
    model.objects.get_or_create(singleton_key=1, defaults={"created_by": "system"})


def _delete_default_settings(apps, schema_editor):
    model = apps.get_model("ops_submissions", "SubmissionControlSettings")
    model.objects.filter(singleton_key=1).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubmissionControlSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                ("control_hour", models.TimeField(default=datetime.time(17, 0))),
                (
                    "required_division_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки контроля сдачи",
                "verbose_name_plural": "Настройки контроля сдачи",
                "db_table": "ops_submission_control_settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("singleton_key", 1)),
                        name="ck_submission_control_settings_singleton",
                    )
                ],
            },
        ),
        migrations.RunPython(_seed_default_settings, _delete_default_settings),
    ]
