# Generated by Django 5.1.15 on 2026-06-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_submissions", "0002_daily_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailysubmission",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dailysubmission",
            name="sanction",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="dailysubmission",
            name="triggered_by_status_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="dailysubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event", "AMENDED"), _negated=True),
                    models.Q(("reason__regex", "\\S"), ("sanction__regex", "\\S")),
                    _connector="OR",
                ),
                name="chk_daily_submission_amended_requires_reason_sanction",
            ),
        ),
    ]
