# Generated by Django 5.1.15 on 2026-07-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_submissions", "0004_tomorrowblockoverride"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissioncontrolsettings",
            name="default_notify_recipient",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="submissioncontrolsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_notify_recipient__regex", "^\\s+$"), _negated=True
                ),
                name="ck_submission_control_settings_duty_not_whitespace",
            ),
        ),
        migrations.CreateModel(
            name="DivisionNotifyRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("division_id", models.UUIDField(unique=True)),
                ("recipient", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Получатель уведомлений подразделения",
                "verbose_name_plural": "Получатели уведомлений подразделений",
                "db_table": "division_notify_recipients",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recipient__regex", "^\\s*$"), _negated=True
                        ),
                        name="ck_division_notify_recipient_not_blank",
                    )
                ],
            },
        ),
    ]
