# Generated by Django 5.1.15 on 2026-07-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("importance_level_code", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
                "db_table": "ops_objects",
            },
        ),
        migrations.CreateModel(
            name="ObjectPassport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("responsible_user_id", models.CharField(blank=True, max_length=100)),
                (
                    "responsible_employee_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("security_notes", models.TextField(blank=True)),
                ("vulnerable_places", models.TextField(blank=True)),
                ("access_routes", models.JSONField(blank=True, default=list)),
                ("entrances", models.JSONField(blank=True, default=list)),
                ("exits", models.JSONField(blank=True, default=list)),
                ("service_entrances", models.JSONField(blank=True, default=list)),
                ("parking_zones", models.JSONField(blank=True, default=list)),
                ("dropoff_zones", models.JSONField(blank=True, default=list)),
                ("elevators", models.JSONField(blank=True, default=list)),
                ("stairs", models.JSONField(blank=True, default=list)),
                ("roofs", models.JSONField(blank=True, default=list)),
                ("basements", models.JSONField(blank=True, default=list)),
                ("technical_rooms", models.JSONField(blank=True, default=list)),
                ("cameras", models.JSONField(blank=True, default=list)),
                ("power_supply", models.TextField(blank=True)),
                ("ventilation", models.TextField(blank=True)),
                ("communication", models.TextField(blank=True)),
                ("internet", models.TextField(blank=True)),
                ("nearby_high_buildings", models.TextField(blank=True)),
                ("public_zones", models.TextField(blank=True)),
                ("crowd_places", models.TextField(blank=True)),
                ("repair_works", models.TextField(blank=True)),
                (
                    "completeness_status",
                    models.CharField(
                        choices=[
                            ("RED", "Не заполнен"),
                            ("YELLOW", "Частично заполнен"),
                            ("GREEN", "Заполнен"),
                        ],
                        default="RED",
                        max_length=10,
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_by", models.CharField(blank=True, max_length=100)),
                (
                    "object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport",
                        to="ops_facilities.object",
                    ),
                ),
            ],
            options={
                "verbose_name": "Паспорт объекта",
                "verbose_name_plural": "Паспорта объектов",
                "db_table": "ops_object_passports",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("completeness_status__in", ["RED", "YELLOW", "GREEN"])
                        ),
                        name="ck_object_passport_completeness_status_choices",
                    )
                ],
            },
        ),
    ]
