# Generated by Django 5.1.15 on 2026-07-31 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_facilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectpassport",
            name="object",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="passport",
                to="ops_facilities.object",
            ),
        ),
        migrations.AddConstraint(
            model_name="object",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="ck_object_latitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="object",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="ck_object_longitude_range",
            ),
        ),
    ]
