# Generated by Django 5.1.15 on 2026-07-31 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_facilities", "0002_alter_objectpassport_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="ops_facilities.object",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сектор",
                "verbose_name_plural": "Секторы",
                "db_table": "ops_object_sectors",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("post_type_code", models.CharField(default="FIXED", max_length=50)),
                ("max_service_minutes", models.PositiveIntegerField(default=480)),
                ("requirements", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("tasks", models.TextField(blank=True)),
                ("features", models.TextField(blank=True)),
                ("location_description", models.TextField(blank=True)),
                ("is_outdoor", models.BooleanField(blank=True, null=True)),
                (
                    "max_continuous_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "min_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("requires_weapon", models.BooleanField(default=False)),
                ("requires_special_equipment", models.BooleanField(default=False)),
                ("requires_uniform", models.BooleanField(default=True)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="ops_facilities.object",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="ops_facilities.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "db_table": "ops_object_posts",
            },
        ),
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(
                fields=("object", "name"), name="uq_object_sector_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                fields=("object", "code"), name="uq_object_post_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_service_minutes__gte", 30), ("max_service_minutes__lte", 1440)
                ),
                name="ck_post_max_service_minutes_range",
            ),
        ),
    ]
