# Generated by Django 5.1.15 on 2026-07-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_facilities", "0003_sector_post_sector_uq_object_sector_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Шаблон чек-листа",
                "verbose_name_plural": "Шаблоны чек-листов",
                "db_table": "ops_object_checklist_templates",
            },
        ),
        migrations.CreateModel(
            name="ChecklistBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_bindings",
                        to="ops_facilities.object",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bindings",
                        to="ops_facilities.checklisttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привязка чек-листа",
                "verbose_name_plural": "Привязки чек-листов",
                "db_table": "ops_object_checklist_bindings",
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("text", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_required", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ops_facilities.checklisttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт чек-листа",
                "verbose_name_plural": "Пункты чек-листа",
                "db_table": "ops_object_checklist_items",
            },
        ),
        migrations.CreateModel(
            name="ChecklistOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "override_type",
                    models.CharField(
                        choices=[
                            ("ADD", "Добавление"),
                            ("MODIFY", "Изменение"),
                            ("DISABLE", "Отключение"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_required", models.BooleanField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="ops_facilities.checklistbinding",
                    ),
                ),
                (
                    "source_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overrides",
                        to="ops_facilities.checklistitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнение чек-листа",
                "verbose_name_plural": "Дополнения чек-листа",
                "db_table": "ops_object_checklist_overrides",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("override_type__in", ["ADD", "MODIFY", "DISABLE"])
                        ),
                        name="ck_checklist_override_type_choices",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="checklistbinding",
            constraint=models.UniqueConstraint(
                fields=("object", "template"), name="uq_object_checklist_binding"
            ),
        ),
    ]
