# Generated by Django 5.1.15 on 2026-07-31 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ops_facilities",
            "0004_checklisttemplate_checklistbinding_checklistitem_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("default_post_type_code", models.CharField(blank=True, max_length=50)),
                (
                    "default_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("rest_after_minutes", models.PositiveIntegerField(default=1440)),
                ("before_duty_minutes", models.PositiveIntegerField(default=0)),
                ("requires_reconnaissance", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_types",
                        to="ops_facilities.object",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид дежурства",
                "verbose_name_plural": "Виды дежурств",
                "db_table": "ops_object_duty_types",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("object", "code"), name="uq_object_duty_type_code"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_duration_minutes__isnull", True),
                            ("default_duration_minutes__gt", 0),
                            _connector="OR",
                        ),
                        name="ck_duty_type_default_duration_minutes_positive",
                    ),
                ],
            },
        ),
    ]
