# Generated by Django 5.1.15 on 2026-07-20 (story 14.3a, split per entity)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_facilities", "0008_checklist_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_bindings",
                        to="ops_facilities.facility",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        db_column="template_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bindings",
                        to="ops_facilities.checklisttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "ops_checklist_bindings",
                "ordering": ["template_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="checklistbinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("facility", "template"),
                name="uq_checklist_binding_facility_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistbinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_default", True)),
                fields=("facility",),
                name="uq_checklist_binding_default_per_facility",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name__isnull", True),
                    ("name__regex", "\\S"),
                    _connector="OR",
                ),
                name="chk_checklist_binding_name_not_blank",
            ),
        ),
    ]
