# Generated by Django 5.1.15 on 2026-07-20 (story 14.3a, split per entity)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_facilities", "0009_checklist_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("override_type", models.CharField(max_length=50)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_required", models.BooleanField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="ops_facilities.checklistbinding",
                    ),
                ),
                (
                    "source_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overrides",
                        to="ops_facilities.checklistitem",
                    ),
                ),
            ],
            options={
                "db_table": "ops_checklist_overrides",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="checklistoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("override_type__in", ["ADD", "MODIFY", "DISABLE"])
                ),
                name="chk_checklist_override_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("override_type", "ADD"), _negated=True),
                    models.Q(
                        ("source_item__isnull", True),
                        ("text__isnull", False),
                        ("text__regex", "\\S"),
                    ),
                    _connector="OR",
                ),
                name="chk_checklist_override_add_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("override_type__in", ["MODIFY", "DISABLE"]),
                        _negated=True,
                    ),
                    ("source_item__isnull", False),
                    _connector="OR",
                ),
                name="chk_checklist_override_bound_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("override_type", "DISABLE"), _negated=True),
                    models.Q(
                        ("category__isnull", True),
                        ("is_required__isnull", True),
                        ("sort_order__isnull", True),
                        ("text__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chk_checklist_override_disable_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("override_type", "MODIFY"), _negated=True),
                    models.Q(
                        ("category__isnull", True),
                        ("is_required__isnull", True),
                        ("sort_order__isnull", True),
                        ("text__isnull", True),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="chk_checklist_override_modify_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("text__isnull", True),
                    ("text__regex", "\\S"),
                    _connector="OR",
                ),
                name="chk_checklist_override_text_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("category__isnull", True),
                    ("category__regex", "\\S"),
                    _connector="OR",
                ),
                name="chk_checklist_override_category_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sort_order__isnull", True),
                    ("sort_order__gte", 0),
                    _connector="OR",
                ),
                name="chk_checklist_override_sort_order_min",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_item__isnull", False)),
                fields=("binding", "source_item"),
                name="uq_checklist_override_binding_source",
            ),
        ),
    ]
