# Generated by Django 5.1.15 on 2026-07-20 13:37

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_facilities", "0010_checklist_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "default_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("rest_after_minutes", models.IntegerField(default=1440)),
                ("before_duty_minutes", models.IntegerField(default=0)),
                ("requires_reconnaissance", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_post_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="default_post_type_code",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duty_types",
                        to="ops_facilities.posttype",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_types",
                        to="ops_facilities.facility",
                    ),
                ),
            ],
            options={
                "db_table": "ops_duty_types",
                "ordering": ["code", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("facility"),
                        django.db.models.functions.text.Lower("code"),
                        condition=models.Q(("is_active", True)),
                        name="uq_duty_type_facility_code",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("code__regex", "\\S")),
                        name="chk_duty_type_code_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name__regex", "\\S")),
                        name="chk_duty_type_name_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_duration_minutes__isnull", True),
                            models.Q(
                                ("default_duration_minutes__gte", 1),
                                ("default_duration_minutes__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="chk_duty_type_duration_min",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rest_after_minutes__gte", 0)),
                        name="chk_duty_type_rest_after_min",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("before_duty_minutes__gte", 0)),
                        name="chk_duty_type_before_duty_min",
                    ),
                ],
            },
        ),
    ]
