# Generated by Django 5.1.15 on 2026-08-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Запись аудита', 'verbose_name_plural': 'Записи аудита'},
        ),
    ]
