"""
Notifications package for the HR system.

This package implements a simple notification model with optional real‑time
delivery via Django Channels.  Notifications are generated by various
events throughout the system (e.g. status updates, secondment requests)
and can be consumed either through the REST API or via WebSocket.
"""
