# Generated by Django 5.1.15 on 2026-06-08 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('divisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_number', models.CharField(default='000000', max_length=20, unique=True)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(default='1970-01-01')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1)),
                ('iin', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('hire_date', models.DateField(default='1970-01-01')),
                ('dismissal_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('working', 'Работает'), ('fired', 'Уволен')], default='working', max_length=10)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.rank')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_temporary', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='employees.employee')),
                ('from_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='divisions.division')),
                ('from_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dictionaries.position')),
                ('to_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='divisions.division')),
                ('to_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dictionaries.position')),
            ],
            options={
                'db_table': 'employee_transfers',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
    ]
