# Generated by Django 5.1.15 on 2026-08-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetransferhistory',
            options={'ordering': ['-transfer_date', '-id'], 'verbose_name': 'История перевода сотрудника', 'verbose_name_plural': 'История переводов сотрудников'},
        ),
    ]
