# Generated by Django 5.1.15 on 2026-07-31 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ops_facilities", "0005_dutytype"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("BULLETIN", "Бюллетень выпущен"),
                            ("RECON", "Рекогносцировка"),
                            ("DEMAND", "Потребность"),
                            ("BROKERAGE", "Брокеридж"),
                            ("PLACEMENT", "Расстановка"),
                            ("APPROVED", "Утверждено"),
                            ("IN_PROGRESS", "Проведение"),
                            ("CLOSED", "Закрыто"),
                            ("CANCELLED", "Отменено"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("senior_employee_id", models.UUIDField(blank=True, null=True)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_events",
                        to="ops_facilities.object",
                    ),
                ),
            ],
            options={
                "verbose_name": "Охранное мероприятие",
                "verbose_name_plural": "Охранные мероприятия",
                "db_table": "ops_security_events",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status_code__in",
                                [
                                    "DRAFT",
                                    "BULLETIN",
                                    "RECON",
                                    "DEMAND",
                                    "BROKERAGE",
                                    "PLACEMENT",
                                    "APPROVED",
                                    "IN_PROGRESS",
                                    "CLOSED",
                                    "CANCELLED",
                                ],
                            )
                        ),
                        name="ck_security_event_status_code_choices",
                    )
                ],
            },
        ),
    ]
