# Generated by Django 5.1.15 on 2026-07-31 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEventChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("label", models.CharField(max_length=255)),
                ("done", models.BooleanField(default=False)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATCHES", "Соответствует"),
                            ("NEEDS_CHANGES", "Требует изменений"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="ops_events.securityevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт чек-листа рекогносцировки",
                "verbose_name_plural": "Пункты чек-листа рекогносцировки",
                "db_table": "ops_security_event_checklist_items",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("result__in", ["MATCHES", "NEEDS_CHANGES"]),
                            ("result__isnull", True),
                            _connector="OR",
                        ),
                        name="ck_security_event_checklist_item_result_choices",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEventSectorPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("sector", models.CharField(max_length=255)),
                ("post", models.CharField(max_length=255)),
                ("task", models.CharField(blank=True, max_length=255)),
                ("need", models.PositiveIntegerField(default=0)),
                ("requirements", models.TextField(blank=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATCHES", "Соответствует"),
                            ("NEEDS_CHANGES", "Требует изменений"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_posts",
                        to="ops_events.securityevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка пересчёта постов/секторов рекогносцировки",
                "verbose_name_plural": "Строки пересчёта постов/секторов",
                "db_table": "ops_security_event_sector_posts",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("result__in", ["MATCHES", "NEEDS_CHANGES"]),
                            ("result__isnull", True),
                            _connector="OR",
                        ),
                        name="ck_security_event_sector_post_result_choices",
                    )
                ],
            },
        ),
    ]
