# Generated by Django 5.1.15 on 2026-07-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0002_securityeventchecklistitem_securityeventsectorpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityevent",
            name="recon_first_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="recon_first_confirmed_by",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
