# Generated by Django 5.1.15 on 2026-07-31 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0003_securityevent_recon_first_confirmed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEventStaffingDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("sector", models.CharField(max_length=255)),
                ("task", models.CharField(blank=True, max_length=255)),
                ("shift", models.CharField(blank=True, max_length=100)),
                ("need", models.PositiveIntegerField(default=0)),
                ("group", models.CharField(blank=True, max_length=255)),
                ("requirements", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing_demands",
                        to="ops_events.securityevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка потребности в силах",
                "verbose_name_plural": "Строки потребности в силах",
                "db_table": "ops_security_event_staffing_demands",
            },
        ),
    ]
