# Generated by Django 5.1.15 on 2026-07-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0004_securityeventstaffingdemand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "db_table": "ops_groups",
                "ordering": ["sort_order", "code"],
            },
        ),
    ]
