# Generated by Django 5.1.15 on 2026-07-31 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0005_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupForceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("requested_count", models.PositiveIntegerField(default=0)),
                ("allocated_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_SENT", "Не отправлен"),
                            ("SENT", "Отправлен"),
                            ("PARTIALLY_ALLOCATED", "Частично выделено"),
                            ("ALLOCATED", "Выделено"),
                        ],
                        default="NOT_SENT",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="force_requests",
                        to="ops_events.securityevent",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="force_requests",
                        to="ops_events.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на Группу",
                "verbose_name_plural": "Запросы на Группы",
                "db_table": "ops_group_force_requests",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "group"),
                        name="uq_group_force_request_event_group",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "NOT_SENT",
                                    "SENT",
                                    "PARTIALLY_ALLOCATED",
                                    "ALLOCATED",
                                ],
                            )
                        ),
                        name="ck_group_force_request_status_choices",
                    ),
                ],
            },
        ),
    ]
