# Generated by Django 5.1.15 on 2026-07-31 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0006_groupforcerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEventDirectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_id", models.UUIDField()),
                ("comment", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_assignments",
                        to="ops_events.securityevent",
                    ),
                ),
                (
                    "sector_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_assignments",
                        to="ops_events.securityeventsectorpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Физнаряд (прямое назначение)",
                "verbose_name_plural": "Физнаряды (прямые назначения)",
                "db_table": "ops_security_event_direct_assignments",
            },
        ),
    ]
