# Generated by Django 5.1.15 on 2026-07-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0007_securityeventdirectassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupforcerequest",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
