# Generated by Django 5.1.15 on 2026-07-31 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0008_groupforcerequest_escalated_at"),
        ("ops_facilities", "0005_dutytype"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("SUBMITTED", "Подано на согласование"),
                            ("RETURNED", "Возвращено на доработку"),
                            ("APPROVED", "Утверждено"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_versions",
                        to="ops_events.securityevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия расстановки",
                "verbose_name_plural": "Версии расстановки",
                "db_table": "ops_assignment_versions",
            },
        ),
        migrations.CreateModel(
            name="PlacementAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_id", models.UUIDField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conflict_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOFT", "Мягкий конфликт"),
                            ("HARD", "Жёсткий конфликт"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="ops_facilities.post",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="ops_events.assignmentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение в расстановке",
                "verbose_name_plural": "Назначения в расстановке",
                "db_table": "ops_placement_assignments",
            },
        ),
        migrations.AddConstraint(
            model_name="assignmentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("event",),
                name="unique_assignment_version_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmentversion",
            constraint=models.UniqueConstraint(
                fields=("event", "version"), name="unique_assignment_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="ck_assignment_version_min",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["DRAFT", "SUBMITTED", "RETURNED", "APPROVED"])
                ),
                name="ck_assignment_version_status_choices",
            ),
        ),
        migrations.AddConstraint(
            model_name="placementassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("conflict_severity", ""),
                    ("conflict_severity__in", ["SOFT", "HARD"]),
                    _connector="OR",
                ),
                name="ck_placement_assignment_conflict_severity_choices",
            ),
        ),
    ]
