# Generated by Django 5.1.15 on 2026-08-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_events', '0009_assignmentversion_placementassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
