# Generated by Django 5.1.15 on 2026-08-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0010_securityevent_ends_at_securityevent_starts_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementassignment",
            name="conflict_codes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
