# Generated by Django 5.1.15 on 2026-08-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0011_placementassignment_conflict_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentversion",
            name="signature_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
