# Generated by Django 5.1.15 on 2026-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_events', '0012_assignmentversion_signature_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementassignment',
            name='ack_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
