# Generated by Django 5.1.15 on 2026-08-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0013_placementassignment_ack_escalated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("BRIEFING", "Инструктаж"), ("DIRECTIVE", "Указание")],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="ops_events.securityevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись журнала штаба",
                "verbose_name_plural": "Записи журнала штаба",
                "db_table": "ops_journal_entries",
                "ordering": ["created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("entry_type__in", ["BRIEFING", "DIRECTIVE"])
                        ),
                        name="ck_journal_entry_type_choices",
                    )
                ],
            },
        ),
    ]
