# Generated by Django 5.1.15 on 2026-08-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0014_journalentry"),
        ("ops_facilities", "0005_dutytype"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="journalentry",
            name="ck_journal_entry_type_choices",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="participant_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="photo_attachment_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incident_journal_entries",
                to="ops_facilities.post",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("BRIEFING", "Инструктаж"),
                    ("DIRECTIVE", "Указание"),
                    ("INCIDENT", "Инцидент"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("entry_type__in", ["BRIEFING", "DIRECTIVE", "INCIDENT"])
                ),
                name="ck_journal_entry_type_choices",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("entry_type", "INCIDENT"), ("post__isnull", False)),
                    models.Q(
                        models.Q(("entry_type", "INCIDENT"), _negated=True),
                        ("post__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_journal_entry_incident_requires_post",
            ),
        ),
    ]
