# Generated by Django 5.1.15 on 2026-08-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ops_events",
            "0015_remove_journalentry_ck_journal_entry_type_choices_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentversion",
            name="is_amendment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignmentversion",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assignmentversion",
            name="sanction",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="assignmentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_amendment", True),
                        ("reason__regex", "\\S"),
                        ("sanction__regex", "\\S"),
                    ),
                    models.Q(("is_amendment", False), ("reason", ""), ("sanction", "")),
                    _connector="OR",
                ),
                name="ck_assignment_version_amendment_requires_reason_sanction",
            ),
        ),
    ]
