# Generated by Django 5.1.15 on 2026-08-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0016_assignmentversion_is_amendment_and_more"),
        ("ops_facilities", "0005_dutytype"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementassignment",
            name="is_unplanned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="placementassignment",
            name="source_division_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementassignment",
            name="source_duty_shift_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="placementassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_unplanned", True),
                        models.Q(
                            ("source_division_id__isnull", False),
                            ("source_duty_shift_id__isnull", False),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("is_unplanned", False),
                        ("source_division_id__isnull", True),
                        ("source_duty_shift_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_placement_assignment_unplanned_requires_source",
            ),
        ),
    ]
