# Generated by Django 5.1.15 on 2026-08-04 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0017_placementassignment_is_unplanned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEventClosureSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("sector", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closure_summaries",
                        to="ops_events.securityevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Итог направления при закрытии",
                "verbose_name_plural": "Итоги направлений при закрытии",
                "db_table": "ops_security_event_closure_summaries",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "sector"),
                        name="uq_security_event_closure_summary_event_sector",
                    )
                ],
            },
        ),
    ]
