# Generated by Django 5.1.15 on 2026-08-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0018_securityeventclosuresummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementAssignmentActual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("actual_start_at", models.DateTimeField()),
                ("actual_end_at", models.DateTimeField()),
                ("recorded_by", models.CharField(blank=True, max_length=100)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_time",
                        to="ops_events.placementassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Факт времени на посту",
                "verbose_name_plural": "Факты времени на постах",
                "db_table": "ops_placement_assignment_actuals",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actual_start_at__lt", models.F("actual_end_at"))
                        ),
                        name="ck_placement_assignment_actual_start_before_end",
                    )
                ],
            },
        ),
    ]
