# Generated by Django 5.1.15 on 2026-08-05 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0019_placementassignmentactual"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("day_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("night_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("computed_at", models.DateTimeField()),
                (
                    "actual",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_hours",
                        to="ops_events.placementassignmentactual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Налёт часов",
                "verbose_name_plural": "Налёт часов",
                "db_table": "ops_service_hours",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("day_hours__gte", 0), ("night_hours__gte", 0)
                        ),
                        name="ck_service_hours_non_negative",
                    )
                ],
            },
        ),
    ]
