# Generated by Django 5.1.15 on 2026-08-05 07:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_events", "0020_servicehours"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicehours",
            name="is_overloaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicehours",
            name="overload_minutes",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
        migrations.AddConstraint(
            model_name="servicehours",
            constraint=models.CheckConstraint(
                condition=models.Q(("overload_minutes__gte", 0)),
                name="ck_service_hours_overload_minutes_non_negative",
            ),
        ),
    ]
