# Generated by Django 5.1.15 on 2026-06-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_statuses", "0001_employee_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusType",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_hard_block", models.BooleanField(default=False)),
                ("priority", models.IntegerField()),
                ("report_column_code", models.CharField(max_length=30)),
                ("counts_in_list", models.BooleanField(default=True)),
                ("counts_in_staff", models.BooleanField(default=True)),
                ("is_ku_owned", models.BooleanField(default=False)),
                ("restricts_editing", models.BooleanField(default=False)),
                ("color", models.CharField(blank=True, default="", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Тип статуса",
                "verbose_name_plural": "Типы статусов",
                "db_table": "ops_status_types",
                "ordering": ["priority", "code"],
            },
        ),
    ]
