# Generated by Django 5.1.15 on 2026-06-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_statuses', '0002_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='document_basis',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='source',
            field=models.CharField(
                choices=[
                    ('USER', 'User'),
                    ('KU_SYNC', 'Ku Sync'),
                    ('OM_AUTO', 'Om Auto'),
                ],
                default='USER',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='source_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
