# Generated by Django 5.1.15 on 2026-06-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_statuses", "0004_statustype_max_duration_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="Override",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_id", models.UUIDField()),
                ("status_type_code", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                ("conflicts", models.JSONField(default=list)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overrides",
                        to="ops_statuses.employeestatus",
                    ),
                ),
            ],
            options={
                "db_table": "ops_status_overrides",
                "indexes": [
                    models.Index(
                        fields=["employee_id", "-created_at"],
                        name="idx_override_emp_created",
                    )
                ],
            },
        ),
    ]
