# Generated by Django 5.1.15 on 2026-06-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_statuses", "0006_status_cancel_facts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secondment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_id", models.UUIDField()),
                ("from_division_id", models.UUIDField()),
                ("to_division_id", models.UUIDField()),
                ("document_basis", models.TextField(blank=True, default="")),
                (
                    "in_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secondment_in",
                        to="ops_statuses.employeestatus",
                    ),
                ),
                (
                    "out_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secondment_out",
                        to="ops_statuses.employeestatus",
                    ),
                ),
            ],
            options={
                "db_table": "ops_status_secondments",
                "indexes": [
                    models.Index(
                        fields=["employee_id", "-created_at"],
                        name="idx_secondment_emp_created",
                    )
                ],
            },
        ),
    ]
