# Generated by Django 5.1.15 on 2026-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_statuses", "0007_secondment"),
    ]

    operations = [
        migrations.AddField(
            model_name="secondment",
            name="return_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secondment",
            name="return_confirmed_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="secondment",
            name="return_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secondment",
            name="return_requested_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
