/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit/logs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["audit_logs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/logs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["audit_logs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/divisions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_divisions_list"];
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["core_divisions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/divisions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_divisions_retrieve"];
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        put: operations["core_divisions_update"];
        post?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        delete: operations["core_divisions_destroy"];
        options?: never;
        head?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        patch: operations["core_divisions_partial_update"];
        trace?: never;
    };
    "/api/core/divisions/{id}/leaf-descendants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_divisions_leaf_descendants_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/employees/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_employees_list"];
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["core_employees_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/employees/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_employees_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        patch: operations["core_employees_partial_update"];
        trace?: never;
    };
    "/api/core/employees/{id}/archive/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["core_employees_archive_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/employees/{id}/restore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["core_employees_restore_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/positions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_positions_list"];
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["core_positions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/positions/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_positions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        patch: operations["core_positions_partial_update"];
        trace?: never;
    };
    "/api/core/ranks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_ranks_list"];
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["core_ranks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/ranks/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_ranks_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        patch: operations["core_ranks_partial_update"];
        trace?: never;
    };
    "/api/core/staffing-slots/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_staffing_slots_list"];
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["core_staffing_slots_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/staffing-slots/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["core_staffing_slots_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        patch: operations["core_staffing_slots_partial_update"];
        trace?: never;
    };
    "/api/core/staffing-slots/{id}/assign-employee/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["core_staffing_slots_assign_employee_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/staffing-slots/{id}/release/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["core_staffing_slots_release_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/vacancies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["core_vacancies_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notifications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/daily-submissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["operations_daily_submissions_retrieve"];
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["operations_daily_submissions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/daily-submissions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        get: operations["operations_daily_submissions_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/daily-submissions/{id}/amend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ViewSet mixin: gate each action on an in-house RBAC permission code.
         *
         *     Subclasses set ``permission_map = {action_name: permission_code}`` (action
         *     name = the ViewSet method, e.g. ``list``/``create``/``partial_update`` or a
         *     custom ``@action`` method like ``archive``/``assign_employee``). The gate
         *     runs in ``initial()`` AFTER ``super().initial()`` — i.e. after DRF
         *     authentication, so the operations seam has populated
         *     ``request.effective_permissions`` (story 2.13). An action absent from the
         *     map is denied (fail-closed); the rbac-matrix completeness test guarantees
         *     every served action is mapped, so a gap surfaces at test time, not in prod.
         *
         *     MRO: list the mixin FIRST (``class FooViewSet(RequirePermissionMixin,
         *     viewsets.ModelViewSet)``) so its ``initial`` wraps the DRF chain. core never
         *     imports operations — the gate reads only request attributes (ARCH#L585).
         */
        post: operations["operations_daily_submissions_amend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/my-permissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["operations_my_permissions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/permissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["operations_permissions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/permissions/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["operations_permissions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["operations_roles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/roles/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["operations_roles_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/temporary-duty/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["operations_temporary_duty_retrieve"];
        put?: never;
        post: operations["operations_temporary_duty_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/temporary-duty/{id}/expire/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["operations_temporary_duty_expire_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/user-roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["operations_user_roles_retrieve"];
        put?: never;
        post: operations["operations_user_roles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/user-roles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["operations_user_roles_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Read-only projection of an audit row — FR-36 fields, snake_case, flat. */
        AuditLog: {
            /** Format: uuid */
            readonly id: string;
            readonly actor_user_id: string;
            readonly action: string;
            readonly entity_type: string;
            /** Format: uuid */
            readonly entity_id: string;
            readonly old_value: unknown;
            readonly new_value: unknown;
            readonly reason: string;
            readonly request_id: string;
            readonly ip_address: string;
            readonly user_agent: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        Division: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            organization: string;
            /** Format: uuid */
            parent?: string | null;
            type_code: string;
            name: string;
            code: string;
            is_active?: boolean;
        };
        DivisionRequest: {
            /** Format: uuid */
            organization: string;
            /** Format: uuid */
            parent?: string | null;
            type_code: string;
            name: string;
            code: string;
            is_active?: boolean;
        };
        Employee: {
            /** Format: uuid */
            readonly id: string;
            external_id?: string | null;
            iin: string;
            readonly full_name: string;
            last_name?: string | null;
            first_name?: string | null;
            middle_name?: string | null;
            rank_code: string;
            readonly rank_index: number;
            position_code: string;
            /** Format: uuid */
            division: string;
            phone?: string | null;
            gender?: (components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            height_cm?: number | null;
            is_active?: boolean;
            is_attached_force?: boolean;
            data_source?: string;
            personnel_number?: string | null;
            /** Format: date */
            birth_date?: string | null;
            photo_file_path?: string | null;
            /** Format: date */
            hire_date?: string | null;
            /** Format: date */
            dismissal_date?: string | null;
            work_phone?: string | null;
            work_email?: string | null;
            personal_phone?: string | null;
            personal_email?: string | null;
            notes?: string | null;
            employment_status?: components["schemas"]["EmploymentStatusEnum"];
        };
        EmployeeRequest: {
            external_id?: string | null;
            iin: string;
            last_name?: string | null;
            first_name?: string | null;
            middle_name?: string | null;
            rank_code: string;
            position_code: string;
            /** Format: uuid */
            division: string;
            phone?: string | null;
            gender?: (components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            height_cm?: number | null;
            is_active?: boolean;
            is_attached_force?: boolean;
            data_source?: string;
            personnel_number?: string | null;
            /** Format: date */
            birth_date?: string | null;
            photo_file_path?: string | null;
            /** Format: date */
            hire_date?: string | null;
            /** Format: date */
            dismissal_date?: string | null;
            work_phone?: string | null;
            work_email?: string | null;
            personal_phone?: string | null;
            personal_email?: string | null;
            notes?: string | null;
            employment_status?: components["schemas"]["EmploymentStatusEnum"];
        };
        /**
         * @description * `WORKING` - Работает
         *     * `FIRED` - Уволен
         *     * `ARCHIVED` - В архиве
         * @enum {string}
         */
        EmploymentStatusEnum: "WORKING" | "FIRED" | "ARCHIVED";
        /**
         * @description * `M` - Мужской
         *     * `F` - Женский
         * @enum {string}
         */
        GenderEnum: "M" | "F";
        /**
         * @description * `SUBMISSION_LAGGING` - Отставание по сдаче
         * @enum {string}
         */
        KindEnum: "SUBMISSION_LAGGING";
        MyPermissionsResponse: {
            permissions: string[];
        };
        /** @description Read-only projection of a notification — flat, snake_case (FR-13). */
        Notification: {
            readonly id: number;
            readonly recipient: string;
            readonly kind: components["schemas"]["KindEnum"];
            /** Format: date */
            readonly business_date: string;
            readonly payload: unknown;
            /** Format: date-time */
            readonly read_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PaginatedAuditLogList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["AuditLog"][];
        };
        PaginatedDivisionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Division"][];
        };
        PaginatedEmployeeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Employee"][];
        };
        PaginatedNotificationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Notification"][];
        };
        PaginatedPermissionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Permission"][];
        };
        PaginatedPositionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Position"][];
        };
        PaginatedRankList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Rank"][];
        };
        PaginatedRoleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Role"][];
        };
        PaginatedStaffingSlotList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StaffingSlot"][];
        };
        PatchedDivisionRequest: {
            /** Format: uuid */
            organization?: string;
            /** Format: uuid */
            parent?: string | null;
            type_code?: string;
            name?: string;
            code?: string;
            is_active?: boolean;
        };
        PatchedEmployeeRequest: {
            external_id?: string | null;
            iin?: string;
            last_name?: string | null;
            first_name?: string | null;
            middle_name?: string | null;
            rank_code?: string;
            position_code?: string;
            /** Format: uuid */
            division?: string;
            phone?: string | null;
            gender?: (components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            height_cm?: number | null;
            is_active?: boolean;
            is_attached_force?: boolean;
            data_source?: string;
            personnel_number?: string | null;
            /** Format: date */
            birth_date?: string | null;
            photo_file_path?: string | null;
            /** Format: date */
            hire_date?: string | null;
            /** Format: date */
            dismissal_date?: string | null;
            work_phone?: string | null;
            work_email?: string | null;
            personal_phone?: string | null;
            personal_email?: string | null;
            notes?: string | null;
            employment_status?: components["schemas"]["EmploymentStatusEnum"];
        };
        PatchedPositionRequest: {
            code?: string;
            name?: string;
            level?: number;
            sort_order?: number;
            is_active?: boolean;
        };
        PatchedRankRequest: {
            code?: string;
            name?: string;
            category?: string | null;
            rank_index?: number;
            is_active?: boolean;
        };
        PatchedStaffingSlotRequest: {
            /** Format: uuid */
            division?: string;
            position_code?: string;
            slot_number?: string | null;
            /** Format: uuid */
            parent_slot?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            valid_from?: string;
            /** Format: date-time */
            valid_to?: string | null;
        };
        Permission: {
            code: string;
            name: string;
            description?: string | null;
            is_active?: boolean;
        };
        Position: {
            code: string;
            name: string;
            level?: number;
            sort_order?: number;
            is_active?: boolean;
        };
        PositionRequest: {
            code: string;
            name: string;
            level?: number;
            sort_order?: number;
            is_active?: boolean;
        };
        Rank: {
            code: string;
            name: string;
            category?: string | null;
            rank_index?: number;
            is_active?: boolean;
        };
        RankRequest: {
            code: string;
            name: string;
            category?: string | null;
            rank_index?: number;
            is_active?: boolean;
        };
        Role: {
            code: string;
            name: string;
            description?: string | null;
            is_active?: boolean;
        };
        StaffingSlot: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            division: string;
            position_code: string;
            slot_number?: string | null;
            /** Format: uuid */
            parent_slot?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            valid_from: string;
            /** Format: date-time */
            valid_to?: string | null;
        };
        StaffingSlotRequest: {
            /** Format: uuid */
            division: string;
            position_code: string;
            slot_number?: string | null;
            /** Format: uuid */
            parent_slot?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            valid_from: string;
            /** Format: date-time */
            valid_to?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_logs_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuditLogList"];
                };
            };
        };
    };
    audit_logs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this audit log. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLog"];
                };
            };
        };
    };
    core_divisions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDivisionList"];
                };
            };
        };
    };
    core_divisions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DivisionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DivisionRequest"];
                "multipart/form-data": components["schemas"]["DivisionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Division"];
                };
            };
        };
    };
    core_divisions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this division. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Division"];
                };
            };
        };
    };
    core_divisions_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this division. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DivisionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DivisionRequest"];
                "multipart/form-data": components["schemas"]["DivisionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Division"];
                };
            };
        };
    };
    core_divisions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this division. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    core_divisions_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this division. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDivisionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDivisionRequest"];
                "multipart/form-data": components["schemas"]["PatchedDivisionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Division"];
                };
            };
        };
    };
    core_divisions_leaf_descendants_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this division. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Division"];
                };
            };
        };
    };
    core_employees_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEmployeeList"];
                };
            };
        };
    };
    core_employees_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmployeeRequest"];
                "multipart/form-data": components["schemas"]["EmployeeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    core_employees_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    core_employees_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEmployeeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEmployeeRequest"];
                "multipart/form-data": components["schemas"]["PatchedEmployeeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    core_employees_archive_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmployeeRequest"];
                "multipart/form-data": components["schemas"]["EmployeeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    core_employees_restore_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmployeeRequest"];
                "multipart/form-data": components["schemas"]["EmployeeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    core_positions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPositionList"];
                };
            };
        };
    };
    core_positions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PositionRequest"];
                "multipart/form-data": components["schemas"]["PositionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"];
                };
            };
        };
    };
    core_positions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this position. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"];
                };
            };
        };
    };
    core_positions_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this position. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPositionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPositionRequest"];
                "multipart/form-data": components["schemas"]["PatchedPositionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"];
                };
            };
        };
    };
    core_ranks_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRankList"];
                };
            };
        };
    };
    core_ranks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RankRequest"];
                "multipart/form-data": components["schemas"]["RankRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rank"];
                };
            };
        };
    };
    core_ranks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this rank. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rank"];
                };
            };
        };
    };
    core_ranks_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this rank. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRankRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRankRequest"];
                "multipart/form-data": components["schemas"]["PatchedRankRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rank"];
                };
            };
        };
    };
    core_staffing_slots_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStaffingSlotList"];
                };
            };
        };
    };
    core_staffing_slots_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffingSlotRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StaffingSlotRequest"];
                "multipart/form-data": components["schemas"]["StaffingSlotRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffingSlot"];
                };
            };
        };
    };
    core_staffing_slots_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this staffing slot. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffingSlot"];
                };
            };
        };
    };
    core_staffing_slots_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this staffing slot. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStaffingSlotRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStaffingSlotRequest"];
                "multipart/form-data": components["schemas"]["PatchedStaffingSlotRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffingSlot"];
                };
            };
        };
    };
    core_staffing_slots_assign_employee_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this staffing slot. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffingSlotRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StaffingSlotRequest"];
                "multipart/form-data": components["schemas"]["StaffingSlotRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffingSlot"];
                };
            };
        };
    };
    core_staffing_slots_release_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this staffing slot. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffingSlotRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StaffingSlotRequest"];
                "multipart/form-data": components["schemas"]["StaffingSlotRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffingSlot"];
                };
            };
        };
    };
    core_vacancies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notifications_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNotificationList"];
                };
            };
        };
    };
    operations_daily_submissions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    operations_daily_submissions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    operations_daily_submissions_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    operations_daily_submissions_amend_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    operations_my_permissions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyPermissionsResponse"];
                };
            };
        };
    };
    operations_permissions_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPermissionList"];
                };
            };
        };
    };
    operations_permissions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this permission. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Permission"];
                };
            };
        };
    };
    operations_roles_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRoleList"];
                };
            };
        };
    };
    operations_roles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this role. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    operations_temporary_duty_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    operations_temporary_duty_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    operations_temporary_duty_expire_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    operations_user_roles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    operations_user_roles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    operations_user_roles_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
