# Generated by Django 5.1.15 on 2026-06-08 16:48

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('divisions', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=10, verbose_name='Статус')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('responsibilities', models.TextField(verbose_name='Обязанности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
                'permissions': [('view_vacancies', 'Просмотр вакансий'), ('view_vacancies_division', 'Просмотр вакансий подразделения'), ('create_vacancy', 'Создание вакансии'), ('create_vacancy_division', 'Создание вакансии в подразделении'), ('edit_vacancy', 'Редактирование вакансии'), ('close_vacancy', 'Закрытие вакансии'), ('fill_vacancy', 'Заполнение вакансии'), ('publish_vacancy', 'Публикация вакансии'), ('unpublish_vacancy', 'Снятие вакансии с публикации')],
            },
        ),
        migrations.CreateModel(
            name='StaffUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Номер слота')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_units', to='divisions.division', verbose_name='Подразделение')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_unit', to='employees.employee', verbose_name='Сотрудник')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='staff_unit.staffunit')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_units', to='dictionaries.position', verbose_name='Должность')),
                ('vacancy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_unit', to='staff_unit.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Штатная единица',
                'verbose_name_plural': 'Штатные единицы',
                'db_table': 'staff_units',
                'permissions': [('view_staffing_table', 'Просмотр штатного расписания'), ('view_staffing_table_division', 'Просмотр штатного расписания подразделения'), ('view_staffing_table_all', 'Просмотр штатного расписания всей организации'), ('view_position_quota', 'Просмотр квоты должностей'), ('view_staffing_statistics', 'Просмотр статистики по штатному расписанию'), ('manage_staffing_table', 'Полное управление штатным расписанием'), ('manage_staffing_table_division', 'Управление штатным расписанием подразделения'), ('create_staffing_position', 'Создание штатной позиции'), ('edit_staffing_position', 'Редактирование штатной позиции'), ('delete_staffing_position', 'Удаление штатной позиции'), ('change_position_quota', 'Изменение квоты должностей'), ('reserve_position', 'Резервирование должности')],
            },
        ),
    ]
