# Generated by Django 5.1.15 on 2026-06-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("recipient", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("SUBMISSION_LAGGING", "Отставание по сдаче")],
                        max_length=50,
                    ),
                ),
                ("business_date", models.DateField()),
                ("payload", models.JSONField(default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "db_table": "notifications",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipient", "kind", "business_date"),
                        name="uq_notification_recipient_kind_date",
                    )
                ],
            },
        ),
    ]
