# Generated by Django 5.1.15 on 2026-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_ix_notif_recipient_recency"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("read_at__isnull", True)),
                fields=["recipient"],
                name="ix_notif_recipient_unread",
            ),
        ),
    ]
