# Generated by Django 5.1.15 on 2026-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_ix_notif_recipient_unread"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="chk_notification_kind",
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SUBMISSION_LAGGING", "Отставание по сдаче"),
                    ("SUBMISSION_THRESHOLD_ALERT", "Порог сдачи не достигнут"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["SUBMISSION_LAGGING", "SUBMISSION_THRESHOLD_ALERT"])
                ),
                name="chk_notification_kind",
            ),
        ),
    ]
