# Generated by Django 5.1.15 on 2026-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0011_remove_notification_chk_notification_kind_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="chk_notification_kind",
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SUBMISSION_LAGGING", "Отставание по сдаче"),
                    ("SUBMISSION_THRESHOLD_ALERT", "Порог сдачи не достигнут"),
                    ("PILOT_PULSE_DIGEST", "Пульс пилота"),
                    (
                        "GROUP_FORCE_REQUEST_ESCALATED",
                        "Эскалация неотработанного запроса",
                    ),
                    ("TEMP_PERMISSION_ACTIVE", "Временное полномочие активно"),
                    ("TEMP_PERMISSION_EXPIRED", "Временное полномочие истекло"),
                    ("ASSIGNMENT_APPROVED", "Расстановка утверждена"),
                    ("ACK_MISSING_ESCALATION", "Ознакомление не получено — эскалация"),
                    ("ACK_REQUIRED", "Требуется ознакомление"),
                    ("ASSIGNMENT_SUBMITTED", "Расстановка подана"),
                    ("ASSIGNMENT_RETURNED", "Расстановка возвращена"),
                    ("REPLACEMENT_CREATED", "Замена в расстановке"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "SUBMISSION_LAGGING",
                            "SUBMISSION_THRESHOLD_ALERT",
                            "PILOT_PULSE_DIGEST",
                            "GROUP_FORCE_REQUEST_ESCALATED",
                            "TEMP_PERMISSION_ACTIVE",
                            "TEMP_PERMISSION_EXPIRED",
                            "ASSIGNMENT_APPROVED",
                            "ACK_MISSING_ESCALATION",
                            "ACK_REQUIRED",
                            "ASSIGNMENT_SUBMITTED",
                            "ASSIGNMENT_RETURNED",
                            "REPLACEMENT_CREATED",
                        ],
                    )
                ),
                name="chk_notification_kind",
            ),
        ),
    ]
