# Generated by Django 5.1.15 on 2026-06-08 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('in_service', 'В строю'), ('vacation', 'Отпуск'), ('leave_by_report', 'Отпуск по рапорту'), ('sick_leave', 'Больничный'), ('business_trip', 'Командировка'), ('training', 'Учёба'), ('competition', 'На соревнованиях'), ('other_absence', 'Отсутствие по иным причинам'), ('on_duty', 'На дежурстве'), ('after_duty', 'После дежурства'), ('seconded_from', 'Прикомандирован из'), ('seconded_to', 'Откомандирован в')], default='in_service', max_length=20, verbose_name='Тип статуса')),
                ('state', models.CharField(choices=[('planned', 'Запланирован'), ('active', 'Активен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='active', max_length=20, verbose_name='Состояние статуса')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('actual_end_date', models.DateField(blank=True, help_text='Используется при досрочном завершении статуса', null=True, verbose_name='Фактическая дата окончания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('early_termination_reason', models.TextField(blank=True, verbose_name='Причина досрочного завершения')),
                ('location', models.CharField(blank=True, help_text='Место командировки/учебы', max_length=255, verbose_name='Место')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_notified', models.BooleanField(default=False, help_text='Уведомление о предстоящем статусе отправлено', verbose_name='Уведомление отправлено')),
                ('auto_applied', models.BooleanField(default=False, help_text='Статус был применен автоматически по расписанию', verbose_name='Применен автоматически')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='employees.employee', verbose_name='Сотрудник')),
                ('related_division', models.ForeignKey(blank=True, help_text='Для прикомандирования - подразделение источник/назначение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisions.division', verbose_name='Связанное подразделение')),
            ],
            options={
                'verbose_name': 'Статус сотрудника',
                'verbose_name_plural': 'Статусы сотрудников',
                'db_table': 'employee_statuses',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Создан'), ('extended', 'Продлен'), ('terminated', 'Досрочно завершен'), ('cancelled', 'Отменен'), ('modified', 'Изменен')], max_length=20, verbose_name='Тип изменения')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='statuses.employeestatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'История изменения статуса',
                'verbose_name_plural': 'История изменений статусов',
                'db_table': 'employee_status_change_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='status_documents/%Y/%m/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='statuses.employeestatus', verbose_name='Статус')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ статуса',
                'verbose_name_plural': 'Документы статусов',
                'db_table': 'employee_status_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employeestatus',
            index=models.Index(fields=['employee', 'state'], name='employee_st_employe_625938_idx'),
        ),
        migrations.AddIndex(
            model_name='employeestatus',
            index=models.Index(fields=['start_date', 'end_date'], name='employee_st_start_d_b2849f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeestatus',
            index=models.Index(fields=['state', 'start_date'], name='employee_st_state_1d494c_idx'),
        ),
    ]
