# Generated by Django 5.1.15 on 2026-06-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_submissions", "0003_amendment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TomorrowBlockOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("business_date", models.DateField()),
                ("reason", models.TextField()),
                ("overridden_by", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Обход блокировки на завтра",
                "verbose_name_plural": "Обходы блокировки на завтра",
                "db_table": "ops_tomorrow_block_overrides",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reason__regex", "^\\s*$"), _negated=True),
                        name="ck_tomorrow_block_override_reason_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("overridden_by__regex", "^\\s*$"), _negated=True
                        ),
                        name="ck_tomorrow_block_override_actor_not_blank",
                    ),
                    models.UniqueConstraint(
                        fields=("business_date",),
                        name="uq_tomorrow_block_override_date",
                    ),
                ],
            },
        ),
    ]
