# Generated by Django 5.1.15 on 2026-07-29 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ops_submissions",
            "0005_submissioncontrolsettings_default_notify_recipient_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="submissioncontrolsettings",
            name="alert_hour",
            field=models.TimeField(default=datetime.time(15, 30)),
        ),
        migrations.AddField(
            model_name="submissioncontrolsettings",
            name="alert_threshold_pct",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddConstraint(
            model_name="submissioncontrolsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("alert_threshold_pct__gte", 1), ("alert_threshold_pct__lte", 100)
                ),
                name="ck_submission_control_settings_alert_threshold_range",
            ),
        ),
    ]
