# Generated by Django 5.1.15 on 2026-08-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
