# Generated by Django 5.1.15 on 2026-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoadCoefficient",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("multiplier", models.DecimalField(decimal_places=3, max_digits=6)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Коэффициент поправки нагрузки",
                "verbose_name_plural": "Коэффициенты поправок нагрузки",
                "db_table": "ops_load_coefficients",
                "ordering": ["code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("multiplier__gt", 0)),
                        name="ck_load_coefficient_multiplier_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("code", ""), _negated=True),
                        name="ck_load_coefficient_code_not_blank",
                    ),
                ],
            },
        ),
    ]
