# Generated by Django 5.1.15 on 2026-07-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_rbac', '0002_rename_content_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarydutypermission',
            name='activated_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
