# Generated by Django 5.1.15 on 2026-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='is_summary_node',
            field=models.BooleanField(default=False),
        ),
    ]
