# Generated by Django 5.1.15 on 2026-06-07 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.division')),
                ('type_code', models.ForeignKey(db_column='type_code', on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='core.divisiontype')),
            ],
            options={
                'db_table': 'core_divisions',
                'indexes': [models.Index(fields=['parent'], name='idx_core_divisions_parent'), models.Index(fields=['organization', 'type_code'], name='idx_core_div_org_type')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='unique_org_division_code')],
            },
        ),
    ]
