# Generated by Django 5.1.15 on 2026-06-07 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_divisionhistoricalslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffingSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slot_number", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing_slots",
                        to="core.division",
                    ),
                ),
                (
                    "parent_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_slots",
                        to="core.staffingslot",
                    ),
                ),
                (
                    "position_code",
                    models.ForeignKey(
                        db_column="position_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staffing_slots",
                        to="core.position",
                    ),
                ),
            ],
            options={
                "db_table": "core_staffing_slots",
                "indexes": [
                    models.Index(
                        fields=["division", "is_active", "valid_from", "valid_to"],
                        name="idx_core_staffing_div",
                    )
                ],
            },
        ),
    ]
