# Generated by Django 5.1.15 on 2026-06-07 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_employeestaffingassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("OPEN", "Открыта"),
                            ("CLOSED", "Закрыта"),
                            ("FROZEN", "Заморожена"),
                        ],
                        default="OPEN",
                        max_length=50,
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "staffing_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="core.staffingslot",
                    ),
                ),
            ],
            options={
                "db_table": "core_vacancies",
            },
        ),
    ]
