# Generated by Django 5.1.15 on 2026-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_divisiontype_sort_order_alter_position_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParallelRunModeSwitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default="default", max_length=100, unique=True),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_parallel_run_mode_switch",
            },
        ),
        migrations.CreateModel(
            name="ParallelRunPilotDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division_id", models.UUIDField(unique=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_parallel_run_pilot_divisions",
            },
        ),
    ]
