# Generated by Django 5.1.15 on 2026-07-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_divisiontype_sort_order_alter_position_level_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="watermark",
            constraint=models.CheckConstraint(
                condition=models.Q(("key", ""), _negated=True),
                name="ck_core_watermarks_key_not_blank",
            ),
        ),
    ]
