# Generated by Django 5.1.15 on 2026-07-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_parallelrunmodeswitch_parallelrunpilotdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='parallelrunmodeswitch',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
