# Generated by Django 5.1.15 on 2026-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_parallel_run_mode_switch_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='parallelrunmodeswitch',
            name='cutover_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
