# Generated by Django 5.1.15 on 2026-07-31 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_parallel_run_mode_switch_cutover_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeOperationalProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("weight_kg", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("clearance_level", models.CharField(blank=True, max_length=100)),
                ("has_weapon_permit", models.BooleanField(default=False)),
                ("weapon_permit_expires_at", models.DateField(blank=True, null=True)),
                ("has_uniform_issued", models.BooleanField(default=False)),
                ("has_special_equipment", models.BooleanField(default=False)),
                ("known_object_codes", models.JSONField(blank=True, default=list)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_profile",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оперативный блок карточки",
                "verbose_name_plural": "Оперативные блоки карточек",
                "db_table": "core_employee_operational_profiles",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("has_weapon_permit", True),
                            ("weapon_permit_expires_at__isnull", True),
                            _connector="OR",
                        ),
                        name="ck_emp_op_profile_weapon_permit_expiry_requires_permit",
                    )
                ],
            },
        ),
    ]
