# Generated by Django 5.1.15 on 2026-07-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_employeeoperationalprofile"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="employeeoperationalprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weight_kg__isnull", True),
                    models.Q(("weight_kg__gte", 30), ("weight_kg__lte", 300)),
                    _connector="OR",
                ),
                name="ck_emp_op_profile_weight_kg_range",
            ),
        ),
    ]
