// Гейт-ассерт стори 8.3 (ARCH-FE-011, фронт-слой двухслойного drift-гейта):
// бэк-слой (pytest test_schema_drift.py в make gate) ловит «API изменили,
// schema.yaml не перегенерили»; этот скрипт ловит «schema.yaml обновили,
// schema.d.ts не перегенерили» И ручную правку schema.d.ts. Механика —
// regen во ВРЕМЕННЫЙ файл + побайтовое сравнение (НЕ git diff: он сравнивает
// с индексом → ложный красный на легитимной незакоммиченной правке).
// Regen строго через CLI дочерним процессом: JS API openapi-typescript
// НЕ пишет AUTO-GENERATED-banner — сравнение было бы вечно красным.
import { execFileSync } from 'node:child_process'
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

// fileURLToPath, не URL.pathname — путь репо содержит кириллицу
const SCHEMA_YAML = fileURLToPath(
  new URL('../../Backend/VAPS/schema.yaml', import.meta.url),
)
const SCHEMA_DTS = fileURLToPath(
  new URL('../src/shared/api/schema.d.ts', import.meta.url),
)
const CLI = fileURLToPath(
  new URL('../node_modules/openapi-typescript/bin/cli.js', import.meta.url),
)

const fail = (msg) => {
  console.error(`schema-check: ${msg}`)
  process.exit(1)
}

// (а) гварды существования/непустоты — отсутствие артефакта не «нечего
// сравнивать», а красный с внятной командой восстановления
if (!existsSync(SCHEMA_YAML) || statSync(SCHEMA_YAML).size === 0)
  fail(
    `Backend/VAPS/schema.yaml отсутствует или пуст (${SCHEMA_YAML}) — run: make schema (в Backend/VAPS)`,
  )
if (!existsSync(SCHEMA_DTS) || statSync(SCHEMA_DTS).size === 0)
  fail(
    `src/shared/api/schema.d.ts отсутствует или пуст — run: npm run generate:api`,
  )

// (б) AUTO-GENERATED-заголовок: CLI пишет «This file was auto-generated by
// openapi-typescript.» первыми строками; его отсутствие = ручная правка или
// генерация через JS API. Отдельный ассерт, не только байтовое сравнение.
const hasAutoHeader = (text) =>
  text
    .split('\n')
    .slice(0, 5)
    .join('\n')
    .toLowerCase()
    .includes('auto-generated')

// негативный контроль (урок вакуумного pass 8.1/8.2): headerless-строка
// обязана НЕ проходить проверку — иначе сам чекер сломан
if (hasAutoHeader('export interface paths {}\n'))
  fail(
    'негативный контроль провален: headerless-содержимое прошло проверку заголовка — чекер вакуумный',
  )

const dtsText = readFileSync(SCHEMA_DTS, 'utf8')
if (!hasAutoHeader(dtsText))
  fail(
    'schema.d.ts без AUTO-GENERATED-заголовка openapi-typescript — файл правлен руками или повреждён. run: npm run generate:api',
  )

// (в) regen через CLI во временный файл → побайтовое сравнение
const tmp = mkdtempSync(join(tmpdir(), 'schema-check-'))
try {
  const fresh = join(tmp, 'schema.d.ts')
  try {
    execFileSync(process.execPath, [CLI, SCHEMA_YAML, '-o', fresh], {
      stdio: ['ignore', 'ignore', 'pipe'],
    })
  } catch (err) {
    fail(
      `openapi-typescript CLI упал: ${err.stderr?.toString() || err.message}`,
    )
  }
  const freshBytes = readFileSync(fresh)
  if (freshBytes.length === 0)
    fail('CLI выдал пустой schema.d.ts — генерация сломана')
  if (!readFileSync(SCHEMA_DTS).equals(freshBytes))
    fail(
      'schema.d.ts расходится с fresh-regen из schema.yaml (schema.yaml обновлён без перегенерации типов или файл правлен руками). run: npm run generate:api',
    )
} finally {
  rmSync(tmp, { recursive: true, force: true })
}

console.log(
  `schema-check: чисто (schema.d.ts байт-в-байт совпадает с regen из schema.yaml, заголовок на месте)`,
)
