# Generated by Django 5.1.15 on 2026-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0003_userrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryDutyPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(max_length=100)),
                ("employee_id", models.UUIDField(blank=True, null=True)),
                (
                    "duty_role_code",
                    models.CharField(
                        choices=[
                            ("OMD", "ОМД"),
                            ("ORGD", "ОРГД"),
                            ("HQ_DUTY", "Дежурный по штабу"),
                            ("OBJECT_SENIOR_DUTY", "Старший по объекту"),
                        ],
                        max_length=50,
                    ),
                ),
                ("scope_division_id", models.UUIDField(blank=True, null=True)),
                ("event_id", models.UUIDField(blank=True, null=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "ops_temporary_duty_permissions",
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_active", "starts_at", "ends_at"],
                        name="idx_ops_temp_duty_user",
                    )
                ],
            },
        ),
    ]
