# Generated by Django 5.1.15 on 2026-07-08 05:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.BigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
                "db_table": "documents_attachments",
                "indexes": [
                    models.Index(fields=["sha256"], name="idx_attachment_sha256")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sha256__regex", "^[0-9a-f]{64}$")),
                        name="chk_attachment_sha256_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("size__gte", 1)),
                        name="chk_attachment_size_min",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("original_name__regex", "\\S")),
                        name="chk_attachment_original_name_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("content_type__regex", "\\S")),
                        name="chk_attachment_content_type_not_blank",
                    ),
                ],
            },
        ),
    ]
