# Generated by Django 5.1.15 on 2026-07-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_type", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Счётчик номеров документов",
                "verbose_name_plural": "Счётчики номеров документов",
                "db_table": "documents_document_sequences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doc_type", "year"),
                        name="uq_document_sequence_doc_type_year",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("last_number__gte", 0)),
                        name="chk_document_sequence_last_number_min",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("year__gte", 2000), ("year__lte", 2200)),
                        name="chk_document_sequence_year_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("doc_type__regex", "\\S")),
                        name="chk_document_sequence_doc_type_not_blank",
                    ),
                ],
            },
        ),
    ]
