# Generated by Django 5.1.15 on 2026-07-08 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_documentsequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("doc_type", models.CharField(max_length=50)),
                ("number", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                ("business_date", models.DateField()),
                ("division_id", models.UUIDField()),
                ("submission_id", models.PositiveBigIntegerField()),
                ("submission_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ISSUED", "Выпущен"), ("SUPERSEDED", "Заменён")],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_documents",
                        to="documents.attachment",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="documents.issueddocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выпуск документа",
                "verbose_name_plural": "Выпуски документов",
                "db_table": "documents_issued_documents",
                "indexes": [
                    models.Index(
                        fields=["division_id", "business_date"],
                        name="idx_issued_document_lookup",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doc_type", "year", "number"),
                        name="uq_issued_document_number",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ISSUED")),
                        fields=("doc_type", "division_id", "business_date"),
                        name="uq_issued_document_current",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["ISSUED", "SUPERSEDED"])),
                        name="chk_issued_document_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("number__gte", 1)),
                        name="chk_issued_document_number_min",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("doc_type__regex", "\\S")),
                        name="chk_issued_document_doc_type_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("supersedes__isnull", False), _negated=True),
                            ("reason__regex", "\\S"),
                            _connector="OR",
                        ),
                        name="chk_issued_document_supersede_reason",
                    ),
                ],
            },
        ),
    ]
