# Generated by Django 5.1.15 on 2026-06-08 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='1970-01-01')),
                ('end_date', models.DateField(default='1970-01-01')),
                ('reason', models.TextField(default='')),
                ('status', models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('cancelled', 'Отменен')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_secondments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('from_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondments_from', to='divisions.division')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_secondments', to=settings.AUTH_USER_MODEL)),
                ('to_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondments_to', to='divisions.division')),
            ],
            options={
                'db_table': 'secondment_requests',
            },
        ),
    ]
