# Generated by Django 5.1.15 on 2026-08-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondmentrequest',
            options={'verbose_name': 'Запрос на прикомандирование', 'verbose_name_plural': 'Запросы на прикомандирование'},
        ),
    ]
