# Generated by Django 5.1.15 on 2026-09-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondments', '0002_alter_secondmentrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondmentrequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Запрос на прикомандирование', 'verbose_name_plural': 'Запросы на прикомандирование'},
        ),
    ]
