# Generated by Django 5.1.15 on 2026-06-08 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('personnel_roster', 'Расход личного состава'), ('division_report', 'Отчет по подразделению'), ('staffing_table', 'Штатное расписание'), ('status_summary', 'Сводка по статусам')], default='personnel_roster', max_length=50)),
                ('report_format', models.CharField(choices=[('docx', 'Word документ'), ('xlsx', 'Excel таблица'), ('pdf', 'PDF документ')], default='pdf', max_length=10)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('job_id', models.CharField(default='0', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('completed', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisions.division')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
