# Generated by Django 5.1.15 on 2026-08-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
    ]
