# Generated by Django 5.1.15 on 2026-08-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_hard_block', models.BooleanField(default=False)),
                ('priority', models.IntegerField()),
                ('report_column_code', models.CharField(max_length=30)),
                ('counts_in_list', models.BooleanField(default=True)),
                ('counts_in_staff', models.BooleanField(default=True)),
                ('is_ku_owned', models.BooleanField(default=False)),
                ('restricts_editing', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('max_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Тип статуса (ОМ)',
                'verbose_name_plural': 'Типы статусов (ОМ)',
                'db_table': 'ops_status_types',
                'ordering': ['priority', 'code'],
            },
        ),
    ]
