# Generated by Django 5.1.15 on 2026-08-04 05:40

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_statustype'),
    ]

    operations = [
        # GiST-равенство по целочисленной колонке employee_id требует
        # btree_gist. ОТКАТ: реверс миграции ДРОПНЕТ расширение — если его
        # использует что-то ещё в этой БД, откатывать выборочно.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='OpsEmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.IntegerField()),
                ('status_type_code', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('USER', 'User'), ('KU_SYNC', 'Ku Sync'), ('OM_AUTO', 'Om Auto')], default='USER', max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('document_basis', models.CharField(blank=True, default='', max_length=255)),
                ('period', models.GeneratedField(db_persist=True, expression=models.Func(models.F('date_start'), models.F('date_end'), models.Value('[)'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), output_field=django.contrib.postgres.fields.ranges.DateRangeField())),
            ],
            options={
                'db_table': 'ops_employee_statuses',
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['employee_id', 'period'], name='gist_status_employee_period')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_start__lt', models.F('date_end'))), name='chk_status_dates'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status_type_code__in', ('SICK_LEAVE', 'LEAVE_BY_REPORT', 'VACATION', 'COMMAND')), ('cancelled_at__isnull', True)), expressions=[(models.F('employee_id'), '='), (models.F('period'), '&&')], name='excl_hard_status_overlap')],
            },
        ),
        migrations.CreateModel(
            name='StatusOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.IntegerField()),
                ('status_type_code', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('conflicts', models.JSONField(default=list)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='operations.opsemployeestatus')),
            ],
            options={
                'db_table': 'ops_status_overrides',
            },
        ),
    ]
