# Generated by Django 5.1.15 on 2026-08-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_opssubmissioncontrolsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsTomorrowBlockOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('business_date', models.DateField(unique=True)),
                ('reason', models.TextField()),
                ('overridden_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Обход блокировки на завтра',
                'verbose_name_plural': 'Обходы блокировки на завтра',
                'db_table': 'ops_tomorrow_block_overrides',
                'constraints': [models.CheckConstraint(condition=models.Q(('reason__regex', '^\\s*$'), _negated=True), name='chk_ops_tomorrow_override_reason'), models.CheckConstraint(condition=models.Q(('overridden_by__regex', '^\\s*$'), _negated=True), name='chk_ops_tomorrow_override_actor')],
            },
        ),
    ]
