# Generated by Django 5.1.15 on 2026-08-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_opstomorrowblockoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustype',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
