# Generated by Django 5.1.15 on 2026-08-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_status_type_is_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('last_materialized_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Водяной знак материализации',
                'verbose_name_plural': 'Водяные знаки материализации',
                'db_table': 'ops_watermarks',
                'constraints': [models.CheckConstraint(condition=models.Q(('key__regex', '^\\s*$'), _negated=True), name='chk_ops_watermark_key')],
            },
        ),
    ]
