# Generated by Django 5.2.4 on 2026-08-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_opsnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsDivisionNotifyRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('division_id', models.IntegerField(unique=True)),
                ('recipient', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Получатель уведомлений подразделения',
                'verbose_name_plural': 'Получатели уведомлений подразделений',
                'db_table': 'ops_division_notify_recipients',
            },
        ),
        migrations.AddField(
            model_name='opssubmissioncontrolsettings',
            name='default_notify_recipient',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='opssubmissioncontrolsettings',
            constraint=models.CheckConstraint(condition=models.Q(('default_notify_recipient__regex', '^\\s+$'), _negated=True), name='chk_ops_control_settings_duty_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='opsdivisionnotifyrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('recipient__regex', '^\\s*$'), _negated=True), name='chk_ops_notify_recipient_not_blank'),
        ),
    ]
