# Generated by Django 5.2.4 on 2026-08-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_opsdocumentsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsIssuedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_type', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('business_date', models.DateField()),
                ('division_id', models.IntegerField()),
                ('submission_id', models.PositiveBigIntegerField()),
                ('submission_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ISSUED', 'Выпущен'), ('SUPERSEDED', 'Заменён')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_documents', to='operations.opsattachment')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='operations.opsissueddocument')),
            ],
            options={
                'verbose_name': 'Выпуск документа',
                'verbose_name_plural': 'Выпуски документов',
                'db_table': 'ops_issued_documents',
                'indexes': [models.Index(fields=['division_id', '-business_date', 'id'], name='idx_ops_issued_doc_registry')],
                'constraints': [models.UniqueConstraint(fields=('doc_type', 'year', 'number'), name='uq_ops_issued_document_number'), models.UniqueConstraint(condition=models.Q(('status', 'ISSUED')), fields=('doc_type', 'division_id', 'business_date'), name='uq_ops_issued_document_current'), models.CheckConstraint(condition=models.Q(('status__in', ['ISSUED', 'SUPERSEDED'])), name='chk_ops_issued_document_status'), models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), ('reason__regex', '\\S'), _connector='OR'), name='chk_ops_issued_document_supersede_reason'), models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='chk_ops_issued_document_number_min'), models.CheckConstraint(condition=models.Q(('year__gte', 2000), ('year__lte', 2200)), name='chk_ops_issued_document_year_range'), models.CheckConstraint(condition=models.Q(('supersedes', models.F('id')), _negated=True), name='chk_ops_issued_document_no_self_supersede')],
            },
        ),
    ]
