# Generated by Django 5.1.15 on 2026-08-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_opsissueddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsSecurityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('object_type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('object_state', models.CharField(choices=[('ACTIVE', 'Действующий'), ('ARCHIVED', 'В архиве')], max_length=20)),
                ('passport_state', models.CharField(choices=[('RED', 'Не оформлен'), ('YELLOW', 'Требует доработки'), ('GREEN', 'Оформлен')], max_length=10)),
            ],
            options={
                'verbose_name': 'Охраняемый объект',
                'verbose_name_plural': 'Охраняемые объекты',
                'db_table': 'ops_security_objects',
                'ordering': ['code', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('object_state__in', ('ACTIVE', 'ARCHIVED'))), name='chk_ops_security_object_state'), models.CheckConstraint(condition=models.Q(('passport_state__in', ('RED', 'YELLOW', 'GREEN'))), name='chk_ops_security_object_passport_state'), models.CheckConstraint(condition=models.Q(('code__regex', '\\S')), name='chk_ops_security_object_code'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='chk_ops_security_object_name')],
            },
        ),
    ]
