# Generated by Django 5.1.15 on 2026-08-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_opssecurityobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsObjectSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('security_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='operations.opssecurityobject')),
            ],
            options={
                'verbose_name': 'Сектор паспорта объекта',
                'verbose_name_plural': 'Секторы паспорта объекта',
                'db_table': 'ops_object_sectors',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpsPassportFreshnessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('verification_interval_days', models.PositiveIntegerField()),
                ('due_soon_percent', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Политика актуальности паспорта',
                'verbose_name_plural': 'Политика актуальности паспорта',
                'db_table': 'ops_passport_freshness_policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('verification_interval_days__gte', 1)), name='chk_ops_freshness_interval_floor'), models.CheckConstraint(condition=models.Q(('due_soon_percent__gte', 0), ('due_soon_percent__lte', 100)), name='chk_ops_freshness_percent_range'), models.CheckConstraint(condition=models.Q(('version__regex', '\\S')), name='chk_ops_freshness_policy_version')],
            },
        ),
        migrations.CreateModel(
            name='OpsPassportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('published_at', models.DateTimeField()),
                ('published_by', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('sectors_snapshot', models.JSONField()),
                ('security_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_versions', to='operations.opssecurityobject')),
            ],
            options={
                'verbose_name': 'Версия паспорта объекта',
                'verbose_name_plural': 'Версии паспорта объекта',
                'db_table': 'ops_passport_versions',
                'ordering': ['version_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpsSecurityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('task', models.CharField(blank=True, max_length=1000)),
                ('requirements', models.CharField(blank=True, max_length=1000)),
                ('position', models.PositiveIntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='operations.opsobjectsector')),
            ],
            options={
                'verbose_name': 'Пост паспорта объекта',
                'verbose_name_plural': 'Посты паспорта объекта',
                'db_table': 'ops_security_posts',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='opsobjectsector',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='chk_ops_object_sector_name'),
        ),
        migrations.AddConstraint(
            model_name='opspassportversion',
            constraint=models.UniqueConstraint(fields=('security_object', 'version_number'), name='uniq_ops_passport_version_number'),
        ),
        migrations.AddConstraint(
            model_name='opspassportversion',
            constraint=models.UniqueConstraint(fields=('security_object', 'effective_from'), name='uniq_ops_passport_version_effective_from'),
        ),
        migrations.AddConstraint(
            model_name='opspassportversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='chk_ops_passport_version_number_floor'),
        ),
        migrations.AddConstraint(
            model_name='opssecuritypost',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='chk_ops_security_post_name'),
        ),
    ]
