# Generated by Django 5.1.15 on 2026-08-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_opsobjectsector_opspassportfreshnesspolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('object_name', models.CharField(max_length=255)),
                ('passport_binding', models.JSONField(null=True)),
                ('business_date', models.DateField()),
                ('stage', models.CharField(choices=[('BULLETIN', 'Бюллетень'), ('RECON', 'Рекогносцировка'), ('DEMAND', 'Потребность'), ('FORCES', 'Запрос сил'), ('PLACEMENT', 'Расстановка'), ('APPROVAL', 'Согласование'), ('ACKNOWLEDGEMENT', 'Ознакомление'), ('CONDUCT', 'Проведение'), ('CLOSED', 'Закрыто')], max_length=20)),
                ('readiness_percent', models.PositiveIntegerField()),
                ('force_need', models.PositiveIntegerField()),
                ('conflicts_count', models.PositiveIntegerField()),
                ('owner_name', models.CharField(max_length=255)),
                ('brief_description', models.TextField(blank=True)),
                ('initial_tasks', models.TextField(blank=True)),
                ('recon_checklist', models.JSONField()),
                ('recon_sector_posts', models.JSONField()),
                ('demand_rows', models.JSONField()),
                ('demand_approved', models.BooleanField()),
                ('force_requests', models.JSONField()),
                ('placement_assignments', models.JSONField()),
                ('approval_status', models.CharField(choices=[('PENDING', 'Ожидает'), ('APPROVED', 'Согласовано'), ('RETURNED', 'Возвращено')], max_length=20)),
                ('approval_comment', models.TextField(blank=True)),
                ('journal_entries', models.JSONField()),
                ('closure_direction_summaries', models.JSONField()),
                ('closed_at', models.DateTimeField(null=True)),
                ('security_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='operations.opssecurityobject')),
            ],
            options={
                'verbose_name': 'Охранное мероприятие',
                'verbose_name_plural': 'Охранные мероприятия',
                'db_table': 'ops_security_events',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stage__in', ('BULLETIN', 'RECON', 'DEMAND', 'FORCES', 'PLACEMENT', 'APPROVAL', 'ACKNOWLEDGEMENT', 'CONDUCT', 'CLOSED'))), name='chk_ops_security_event_stage'), models.CheckConstraint(condition=models.Q(('approval_status__in', ('PENDING', 'APPROVED', 'RETURNED'))), name='chk_ops_security_event_approval'), models.CheckConstraint(condition=models.Q(('readiness_percent__gte', 0), ('readiness_percent__lte', 100)), name='chk_ops_security_event_readiness_range'), models.CheckConstraint(condition=models.Q(('code__regex', '\\S')), name='chk_ops_security_event_code'), models.CheckConstraint(condition=models.Q(('title__regex', '\\S')), name='chk_ops_security_event_title')],
            },
        ),
    ]
