# Generated by Django 5.1.15 on 2026-08-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_opsevaluationevent_opsratedparticipant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsAnalyticsMetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_code', models.CharField(max_length=100, unique=True)),
                ('safe_label', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('warning_from', models.IntegerField(null=True)),
                ('critical_from', models.IntegerField(null=True)),
                ('drilldown_available', models.BooleanField()),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Показатель аналитики службы',
                'verbose_name_plural': 'Показатели аналитики службы',
                'db_table': 'ops_analytics_metric_definitions',
                'ordering': ['position', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit__in', ('COUNT', 'PERCENT', 'MINUTES', 'HOURS'))), name='chk_ops_metric_unit')],
            },
        ),
        migrations.CreateModel(
            name='OpsAnalyticsPeriodPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('preset_code', models.CharField(max_length=50, unique=True)),
                ('safe_label', models.CharField(max_length=255)),
                ('offset_days', models.IntegerField()),
                ('length_days', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Пресет периода аналитики',
                'verbose_name_plural': 'Пресеты периодов аналитики',
                'db_table': 'ops_analytics_period_presets',
                'ordering': ['position', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('length_days__gte', 1)), name='chk_ops_preset_length_floor')],
            },
        ),
        migrations.CreateModel(
            name='OpsAttentionDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('category_code', models.CharField(max_length=100, unique=True)),
                ('measure', models.CharField(max_length=50)),
                ('title_code', models.CharField(max_length=50)),
                ('safe_description_template', models.TextField()),
                ('parameter', models.IntegerField()),
                ('warning_from', models.IntegerField(null=True)),
                ('critical_from', models.IntegerField(null=True)),
                ('base_severity', models.CharField(max_length=20)),
                ('target_route', models.CharField(max_length=255, null=True)),
                ('target_permission', models.CharField(max_length=100, null=True)),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Детектор внимания',
                'verbose_name_plural': 'Детекторы внимания',
                'db_table': 'ops_attention_detectors',
                'ordering': ['position', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('measure__in', ('ACKNOWLEDGEMENT_MISSING', 'CONFLICT_SHARE', 'UNFINISHED_OVERDUE', 'UNCONFIRMED_OVERDUE', 'SOURCE_AGE'))), name='chk_ops_detector_measure'), models.CheckConstraint(condition=models.Q(('title_code__in', ('VERIFICATION_REQUIRED', 'DATA_UNCONFIRMED', 'THRESHOLD_EXCEEDED', 'UNFINISHED_PROCESSES', 'SOURCE_NOT_UPDATED'))), name='chk_ops_detector_title'), models.CheckConstraint(condition=models.Q(('base_severity__in', ('CRITICAL', 'WARNING', 'INFO'))), name='chk_ops_detector_severity')],
            },
        ),
        migrations.CreateModel(
            name='OpsSecurityEventTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('from_stage', models.CharField(max_length=20, null=True)),
                ('to_stage', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='operations.opssecurityevent')),
            ],
            options={
                'verbose_name': 'Переход стадии ОМ',
                'verbose_name_plural': 'Переходы стадий ОМ',
                'db_table': 'ops_security_event_transitions',
                'ordering': ['occurred_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('to_stage__in', ('BULLETIN', 'RECON', 'DEMAND', 'FORCES', 'PLACEMENT', 'APPROVAL', 'ACKNOWLEDGEMENT', 'CONDUCT', 'CLOSED'))), name='chk_ops_event_transition_to_stage'), models.CheckConstraint(condition=models.Q(('kind__in', ('FORWARD', 'RETURN'))), name='chk_ops_event_transition_kind')],
            },
        ),
    ]
