# Generated by Django 5.1.15 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_opsanalyticsmetricdefinition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsServiceReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('report_type_code', models.CharField(max_length=100, unique=True)),
                ('safe_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('formats', models.JSONField()),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Тип служебного отчёта',
                'verbose_name_plural': 'Типы служебных отчётов',
                'db_table': 'ops_service_report_types',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpsServiceReportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('artifact_code', models.CharField(max_length=100, unique=True)),
                ('job_code', models.CharField(max_length=100)),
                ('report_type_code', models.CharField(max_length=100)),
                ('safe_title', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=10)),
                ('revision', models.IntegerField()),
                ('generated_at', models.DateTimeField()),
                ('generated_by', models.CharField(max_length=255)),
                ('param_from', models.DateField()),
                ('param_to', models.DateField()),
                ('calculation_version', models.CharField(max_length=100)),
                ('masking_policy_version', models.CharField(max_length=100)),
                ('retention_policy_version', models.CharField(max_length=100)),
                ('sensitive', models.BooleanField()),
                ('file_size', models.IntegerField()),
                ('hash', models.CharField(max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Артефакт служебного отчёта',
                'verbose_name_plural': 'Артефакты служебных отчётов',
                'db_table': 'ops_service_report_artifacts',
                'ordering': ['-generated_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='chk_ops_report_artifact_revision')],
            },
        ),
        migrations.CreateModel(
            name='OpsServiceReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('job_code', models.CharField(max_length=100, unique=True)),
                ('report_type_code', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('progress_percent', models.IntegerField(null=True)),
                ('requested_at', models.DateTimeField()),
                ('created_by_user_id', models.CharField(max_length=255)),
                ('created_by_label', models.CharField(max_length=255)),
                ('completed_at', models.DateTimeField(null=True)),
                ('failure_code', models.CharField(max_length=100, null=True)),
                ('safe_failure_message', models.TextField(null=True)),
                ('artifact_code', models.CharField(max_length=100, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('sensitive', models.BooleanField()),
                ('param_from', models.DateField()),
                ('param_to', models.DateField()),
            ],
            options={
                'verbose_name': 'Работа служебного отчёта',
                'verbose_name_plural': 'Работы служебных отчётов',
                'db_table': 'ops_service_report_jobs',
                'ordering': ['-requested_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))), name='chk_ops_report_job_state')],
            },
        ),
    ]
