# Generated by Django 5.1.15 on 2026-08-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_opssecurityobject_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityevent',
            name='approval_route',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
