# Generated by Django 5.1.15 on 2026-08-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_opslegaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityevent',
            name='chief_employee_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opssecurityevent',
            name='chief_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opssecurityevent',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opssecurityevent',
            name='kind',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'Внутреннее'), ('FOREIGN', 'С участием иностранцев')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opssecurityevent',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opssecurityevent',
            name='protected_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='operations.opsprotectedperson'),
        ),
        migrations.AddField(
            model_name='opssecurityevent',
            name='protected_person_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='opssecurityevent',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('INTERNAL', 'FOREIGN')), ('kind__isnull', True), _connector='OR'), name='chk_ops_security_event_kind'),
        ),
    ]
