# Generated by Django 5.1.15 on 2026-08-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_security_event_bulletin_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsSecurityEventVisitObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('object_name', models.CharField(max_length=255)),
                ('passport_binding', models.JSONField(null=True)),
                ('protected_person_name', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_objects', to='operations.opssecurityevent')),
                ('protected_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_visits', to='operations.opsprotectedperson')),
                ('security_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_visits', to='operations.opssecurityobject')),
            ],
            options={
                'verbose_name': 'Объект посещения ОМ',
                'verbose_name_plural': 'Объекты посещения ОМ',
                'db_table': 'ops_security_event_visit_objects',
                'ordering': ['position', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('object_name__regex', '\\S')), name='chk_ops_event_visit_object_name'), models.UniqueConstraint(condition=models.Q(('security_object__isnull', False)), fields=('event', 'security_object'), name='uniq_ops_event_visit_object')],
            },
        ),
    ]
