# Generated by Django 5.1.15 on 2026-08-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_backfill_visit_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityevent',
            name='recon_force_request',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opssecurityevent',
            name='recon_force_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
