# Generated by Django 5.1.15 on 2026-08-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0041_dedupe_recon_post_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityevent',
            name='approval_remarks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opssecurityevent',
            name='approval_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
    ]
