# Generated by Django 5.1.15 on 2026-08-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0044_force_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsauditlog',
            name='entity_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opsauditlog',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
