# Generated by Django 5.1.15 on 2026-08-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0052_opsvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsEventVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_label', models.CharField(max_length=255)),
                ('callsign', models.CharField(blank=True, max_length=64)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='operations.opssecurityevent')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_allocations', to='operations.opsvehicle')),
            ],
            options={
                'verbose_name': 'выделенный транспорт',
                'verbose_name_plural': 'Выделенный транспорт',
                'db_table': 'ops_event_vehicles',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'vehicle'), name='uniq_ops_event_vehicle')],
            },
        ),
    ]
