# Generated by Django 5.1.15 on 2026-08-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0053_opseventvehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opsauditlog',
            options={'verbose_name': 'Журнал раздела ОМ', 'verbose_name_plural': 'Журналы раздела ОМ'},
        ),
        migrations.AlterModelOptions(
            name='opsemployeestatus',
            options={'verbose_name': 'Статус сотрудника (ОМ)', 'verbose_name_plural': 'Статусы сотрудников (ОМ)'},
        ),
        migrations.AlterModelOptions(
            name='opsgvosummarypatch',
            options={'ordering': ['event_id'], 'verbose_name': 'Правка сводки ГВО', 'verbose_name_plural': 'Правки сводок ГВО'},
        ),
        migrations.AlterModelOptions(
            name='opslegaldocument',
            options={'ordering': ['kind', 'code', 'id'], 'verbose_name': 'Закон об ОМ', 'verbose_name_plural': 'Законы об ОМ'},
        ),
        migrations.AlterModelOptions(
            name='opsprotectedperson',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Охраняемое лицо', 'verbose_name_plural': 'Охраняемые лица'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Право раздела ОМ', 'verbose_name_plural': 'Права раздела ОМ'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль раздела ОМ', 'verbose_name_plural': 'Роли раздела ОМ'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Право роли (ОМ)', 'verbose_name_plural': 'Права ролей (ОМ)'},
        ),
        migrations.AlterModelOptions(
            name='secondment',
            options={'verbose_name': 'Прикомандирование (ОМ)', 'verbose_name_plural': 'Прикомандирования (ОМ)'},
        ),
        migrations.AlterModelOptions(
            name='statusoverride',
            options={'verbose_name': 'Обход статуса', 'verbose_name_plural': 'Обходы статусов'},
        ),
        migrations.AlterModelOptions(
            name='temporarydutypermission',
            options={'verbose_name': 'Временное право наряда', 'verbose_name_plural': 'Временные права наряда'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Роль пользователя (ОМ)', 'verbose_name_plural': 'Роли пользователей (ОМ)'},
        ),
    ]
