# Generated by Django 5.1.15 on 2026-08-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0054_alter_opsauditlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opsdictionaryentry',
            name='chk_ops_dictionary_code',
        ),
        migrations.AddConstraint(
            model_name='opsdictionaryentry',
            constraint=models.CheckConstraint(condition=models.Q(('dictionary_code__in', ('RETURN_REASONS', 'POST_REQUIREMENTS', 'SEASONAL_CORRECTIONS', 'JOURNAL_ENTRY_TYPES', 'POST_REQUIREMENT_GROUPS', 'PLACEMENT_ROLES'))), name='chk_ops_dictionary_code'),
        ),
    ]
