# Generated by Django 5.1.15 on 2026-08-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0058_notification_kind_event_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='opscombatdutyshift',
            name='group_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
