# Generated by Django 5.1.15 on 2026-09-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0076_notification_kind_placement_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityeventvisitobject',
            name='closing_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
