# Generated by Django 5.1.15 on 2026-09-03 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0079_event_location_structure_and_person_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsBulletinIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('as_of', models.DateTimeField(db_index=True)),
                ('issued_by', models.CharField(blank=True, default='', max_length=200)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_issues', to='operations.opsattachment')),
            ],
            options={
                'verbose_name': 'Выпуск бюллетеня',
                'verbose_name_plural': 'Выпуски бюллетеня',
                'db_table': 'ops_bulletin_issues',
                'ordering': ['-as_of', '-id'],
            },
        ),
    ]
