# Generated by Django 5.1.15 on 2026-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0080_bulletin_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsApprovalRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.PositiveIntegerField()),
                ('role_label', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, default='', max_length=200)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Шаг маршрута согласования',
                'verbose_name_plural': 'Маршрут согласования',
                'db_table': 'ops_approval_route_steps',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('position',), name='uniq_ops_approval_route_position')],
            },
        ),
    ]
