# Generated by Django 5.1.15 on 2026-09-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0083_notification_kind_ack_due_soon'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opspolicysectionversion',
            name='chk_ops_section_version_code',
        ),
        migrations.RemoveConstraint(
            model_name='opspolicysetting',
            name='chk_ops_setting_section',
        ),
        migrations.AddConstraint(
            model_name='opspolicysectionversion',
            constraint=models.CheckConstraint(condition=models.Q(('section_code__in', ('CONFLICT_RULES', 'PASSPORT_FRESHNESS', 'RATING_POLICY', 'ANALYTICS_LIMITS', 'LOAD_POLICY', 'ATTENTION_POLICY', 'REPORT_LIMITS', 'APPROVAL_POLICY'))), name='chk_ops_section_version_code'),
        ),
        migrations.AddConstraint(
            model_name='opspolicysetting',
            constraint=models.CheckConstraint(condition=models.Q(('section_code__in', ('CONFLICT_RULES', 'PASSPORT_FRESHNESS', 'RATING_POLICY', 'ANALYTICS_LIMITS', 'LOAD_POLICY', 'ATTENTION_POLICY', 'REPORT_LIMITS', 'APPROVAL_POLICY'))), name='chk_ops_setting_section'),
        ),
    ]
