# Generated by Django 5.1.15 on 2026-09-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0086_foreign_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityevent',
            name='closing_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
