# Generated by Django 5.1.15 on 2026-08-03 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код права (например, view_staffing_table)', max_length=100, unique=True, verbose_name='Код права')),
                ('name', models.CharField(help_text='Человекочитаемое название права', max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('staffing', 'Штатное расписание'), ('vacancy', 'Вакансии'), ('employee', 'Сотрудники'), ('status', 'Статусы'), ('secondment', 'Прикомандирование'), ('structure', 'Структура организации'), ('report', 'Отчёты'), ('admin', 'Администрирование'), ('audit', 'Аудит')], help_text='Категория для группировки прав', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, help_text='Подробное описание права', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Можно деактивировать право без удаления', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
                'db_table': 'permissions',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код роли (например, ROLE_1, ROLE_2)', max_length=20, unique=True, verbose_name='Код роли')),
                ('name', models.CharField(help_text='Человекочитаемое название роли', max_length=100, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, help_text='Подробное описание роли и её полномочий', verbose_name='Описание')),
                ('hierarchy_level', models.IntegerField(blank=True, choices=[(None, 'Не привязан к уровню'), (0, 'Вся организация'), (1, 'Департамент'), (2, 'Управление'), (3, 'Отдел')], help_text='0=вся организация, 1=департамент, 2=управление, 3=отдел, null=не привязан к уровню', null=True, verbose_name='Уровень иерархии')),
                ('requires_scope', models.BooleanField(default=True, help_text='Должна ли роль иметь привязку к подразделению', verbose_name='Требует область видимости')),
                ('can_edit_statuses', models.BooleanField(default=False, help_text='Может ли роль изменять статусы сотрудников', verbose_name='Может редактировать статусы')),
                ('is_active', models.BooleanField(default=True, help_text='Можно деактивировать роль без удаления', verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, help_text='Для упорядочивания ролей в списках', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'roles',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seconded', models.BooleanField(default=False, verbose_name='Откомандирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('role', models.ForeignKey(help_text='Роль пользователя из системы RBAC', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='common.role', verbose_name='Роль')),
                ('scope_division', models.ForeignKey(blank=True, help_text='Департамент/Управление/Отдел в зависимости от роли', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_users', to='divisions.division', verbose_name='Подразделение (область видимости)')),
                ('seconded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seconded_users', to='divisions.division', verbose_name='Откомандирован в')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'db_table': 'user_roles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('organization', 'Вся организация'), ('department', 'Департамент'), ('own_division', 'Собственное подразделение'), ('custom', 'Пользовательская область')], default='own_division', help_text='На каком уровне применяется право', max_length=20, verbose_name='Тип области видимости')),
                ('is_active', models.BooleanField(default=True, help_text='Можно временно отключить право у роли', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='common.permission', verbose_name='Право')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='common.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Право роли',
                'verbose_name_plural': 'Права ролей',
                'db_table': 'role_permissions',
                'ordering': ['role__code', 'permission__category', 'permission__code'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
