"""Снос старого каталога ролей (Plane №352, Ш-6).

🔴 ОТКАТА У ЭТОЙ МИГРАЦИИ НЕТ В ТОМ СМЫСЛЕ, В КАКОМ ОН ОБЫЧНО ЕСТЬ. Django
умеет создать таблицы обратно (`migrate common 0002`), но ДАННЫЕ в них не
вернутся: назначения ролей исчезают вместе со строками. Это осознанно и
безопасно ровно потому, что читателей у них не осталось ни одного — их
снимали пять предыдущих шагов плана, а не этот:

* Ш-1 — видимость меню переехала на права раздела;
* Ш-2 — область портальных экранов считается по разделу;
* Ш-3 — права штатки и вакансий переехали на коды раздела;
* Ш-4 — токен перестал нести роль и область, клиент читает `my-permissions`;
* Ш-5 — семь ролей заказчика получили права раздела, `seed_access_matrix`
  перестал выдавать портальную роль.

ЧТО ПРОВЕРИТЬ ПЕРЕД ПРИМЕНЕНИЕМ НА БОЕВОЙ БАЗЕ: у каждой действующей учётки
есть хотя бы один грант роли РАЗДЕЛА (`ops_user_roles`). Учётка без грантов
после этой миграции войдёт в систему, но не увидит ни одного модуля — и это
будет честно показано подписью «Роль не назначена» в шапке (Ш-4), а не
пустым экраном.
"""
# Generated by Django 5.1.15 on 2026-08-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_role_overview_at_department'),
    ]

    operations = [
        # 🔴 ПОРЯДОК ПРАВЛЕН РУКАМИ. Автогенератор поставил снятие
        # `unique_together` ПОСЛЕ удаления полей, из которых оно составлено, и
        # миграция падала на `KeyError: 'role'`: Django не может пересобрать
        # ограничение по полю, которого уже нет. Ограничение снимается первым.
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='scope_division',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='seconded_to',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
