# Generated by Django 5.1.15 on 2026-07-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParallelRunDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateField(unique=True)),
                ("status", models.CharField(max_length=32)),
                ("blocking_count", models.IntegerField(default=0)),
                ("total_diffs", models.IntegerField(default=0)),
                ("ran_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "parallel_run_days",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status", ""), _negated=True),
                        name="chk_parallel_run_day_status_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("blocking_count__gte", 0), ("total_diffs__gte", 0)
                        ),
                        name="chk_parallel_run_day_counts_nonneg",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParallelRunDiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateField()),
                ("division_code", models.CharField(max_length=100)),
                ("column_code", models.CharField(max_length=100)),
                ("donor_value", models.IntegerField()),
                ("vaps_value", models.IntegerField()),
                ("delta", models.IntegerField()),
                ("category", models.CharField(max_length=64)),
                ("is_blocking", models.BooleanField()),
                ("pending_signature", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "parallel_run_diffs",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_date", "division_code", "column_code"),
                        name="uq_parallel_run_diff_cell",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("category", ""), _negated=True),
                        name="chk_parallel_run_diff_category_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("donor_value__gte", 0), ("vaps_value__gte", 0)
                        ),
                        name="chk_parallel_run_diff_values_nonneg",
                    ),
                ],
            },
        ),
    ]
