# Initial migration for the audit app — Story 1.1 (audit-consolidation epic).
# Generated by makemigrations, then hand-trimmed to the target AuditLog model
# only; the legacy AuditEntry model is migrated by a later story.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Story 1.1: only the target AuditLog model is migrated here. The legacy
        # AuditEntry model is intentionally left without a migration (handled by
        # later stories in the audit-consolidation epic).
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('STATUS_CHANGE', 'Status Change'), ('TRANSFER', 'Transfer'), ('SECONDMENT', 'Secondment'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REPORT_GENERATED', 'Report Generated'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('ESCALATION', 'Escalation')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'user'], name='audit_audit_timesta_283448_idx'), models.Index(fields=['action_type'], name='audit_audit_action__dd3a3c_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
    ]
