# Generated by Django 5.1.15 on 2026-07-31 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ops_facilities", "0005_dutytype"),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "status_code",
                    models.CharField(
                        choices=[("DRAFT", "Черновик"), ("APPROVED", "Утверждён")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_plans",
                        to="ops_facilities.object",
                    ),
                ),
            ],
            options={
                "verbose_name": "План дежурств",
                "verbose_name_plural": "Планы дежурств",
                "db_table": "ops_duty_plans",
            },
        ),
        migrations.CreateModel(
            name="DutyShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_id", models.UUIDField()),
                ("duty_role_code", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "duty_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_shifts",
                        to="ops_facilities.dutytype",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="ops_duties.dutyplan",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_shifts",
                        to="ops_facilities.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена",
                "verbose_name_plural": "Смены",
                "db_table": "ops_duty_shifts",
            },
        ),
        migrations.AddConstraint(
            model_name="dutyplan",
            constraint=models.UniqueConstraint(
                fields=("object", "year", "month"), name="uq_duty_plan_object_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="dutyplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 2026), ("year__lte", 2100)),
                name="ck_duty_plan_year_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="dutyplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                name="ck_duty_plan_month_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="dutyplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("status_code__in", ["DRAFT", "APPROVED"])),
                name="ck_duty_plan_status_code_choices",
            ),
        ),
        migrations.AddIndex(
            model_name="dutyshift",
            index=models.Index(
                fields=["employee_id", "starts_at", "ends_at"],
                name="idx_ops_duty_employee_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="dutyshift",
            constraint=models.CheckConstraint(
                condition=models.Q(("starts_at__lt", models.F("ends_at"))),
                name="ck_duty_shift_starts_before_ends",
            ),
        ),
    ]
