# Generated by Django 5.1.15 on 2026-07-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_duties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyshift",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dutyshift",
            name="cancelled_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dutyshift",
            name="cancelled_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
