# Generated by Django 5.1.15 on 2026-09-05 17:34

"""Позывной сотрудника (`[МД-10]`, Plane №456).

Бюллетень печатает старшего мероприятия как «Фамилия / позывной», а позывного
у кадровой записи не было вовсе: он был только у охраняемых лиц и у транспорта.

Бэкфилла тут нет и быть не может: позывной — новый факт о человеке, а не
пересчёт старого. У всех заведённых сотрудников поле остаётся пустым, и
бюллетень для них печатает прежнее «Фамилия И.» — ровно то же, что печатал до
этой миграции. То есть выкат ничего не меняет, пока позывной не вписали.

Откат безопасен: поле снимается, читатели возвращаются к «Фамилия И.».
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeetransferhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='callsign',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
