# Generated by Django 5.1.15 on 2026-06-11 13:45

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # gist equality on the uuid column requires btree_gist.
        # Rollback note: reversing this migration DROPs the btree_gist
        # extension for the whole database, not just this app — do not
        # reverse on a shared cluster. Applying requires a role allowed to
        # CREATE EXTENSION (compose runs as the `vaps` superuser; on managed
        # Postgres the extension may need to be pre-installed by the DBA).
        BtreeGistExtension(),
        migrations.CreateModel(
            name="EmployeeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_id", models.UUIDField()),
                ("status_type_code", models.CharField(max_length=50)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("date_start"),
                            models.F("date_end"),
                            models.Value("[)"),
                            function="daterange",
                            output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                        ),
                        output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                    ),
                ),
            ],
            options={
                "db_table": "ops_employee_statuses",
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["employee_id", "period"],
                        name="gist_status_employee_period",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("date_start__lt", models.F("date_end"))),
                        name="chk_status_dates",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(
                            (
                                "status_type_code__in",
                                (
                                    "SICK_LEAVE",
                                    "LEAVE_BY_REPORT",
                                    "VACATION",
                                    "COMMAND",
                                ),
                            ),
                            ("cancelled_at__isnull", True),
                        ),
                        expressions=[
                            (models.F("employee_id"), "="),
                            (models.F("period"), "&&"),
                        ],
                        name="excl_hard_status_overlap",
                    ),
                ],
            },
        ),
    ]
