# Generated by Django 5.1.15 on 2026-06-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_statuses', '0003_status_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustype',
            name='max_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
