# Generated by Django 5.1.15 on 2026-06-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_statuses', '0005_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='cancelled_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
