# Generated by Django 5.1.15 on 2026-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RosterReconciliationSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division_id", models.UUIDField()),
                ("business_date", models.DateField()),
                ("signed_by", models.CharField(max_length=100)),
                ("signed_at", models.DateTimeField()),
                ("discrepancy_count", models.IntegerField()),
                ("notes", models.CharField(blank=True, default="", max_length=1000)),
            ],
            options={
                "db_table": "migration_legacy_roster_reconciliation_signature",
                "indexes": [
                    models.Index(
                        fields=["division_id", "business_date", "signed_at"],
                        name="migration_l_divisio_488a14_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("discrepancy_count__gte", 0)),
                        name="chk_roster_reconciliation_discrepancy_count_non_negative",
                    )
                ],
            },
        ),
    ]
