# Generated by Django 5.1.15 on 2026-07-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("user_id", models.CharField(max_length=100)),
                ("screen_path", models.CharField(max_length=255)),
                ("app_version", models.CharField(blank=True, max_length=100)),
                ("build_sha", models.CharField(blank=True, max_length=100)),
                ("last_request_ids", models.JSONField(blank=True, default=list)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "ops_bug_reports",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="idx_ops_bugreports_created"
                    )
                ],
            },
        ),
    ]
