# Generated by Django 5.1.15 on 2026-07-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops_bugreports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugreport",
            name="resolution_summary",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="bugreport",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bugreport",
            name="resolved_in_version",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
