# Generated by Django 5.1.15 on 2026-06-07 16:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('iin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='ИИН должен состоять из 12 цифр.', regex='^[0-9]{12}$')])),
                ('full_name', models.CharField(max_length=255)),
                ('rank_code', models.CharField(max_length=50)),
                ('rank_index', models.IntegerField(default=0)),
                ('position_code', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(230)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_attached_force', models.BooleanField(default=False)),
                ('data_source', models.CharField(default='STUB', max_length=50)),
                ('separated_at', models.DateTimeField(blank=True, null=True)),
                ('personnel_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo_file_path', models.TextField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('dismissal_date', models.DateField(blank=True, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('work_email', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_email', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('WORKING', 'Работает'), ('FIRED', 'Уволен'), ('ARCHIVED', 'В архиве')], default='WORKING', max_length=50)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.division')),
            ],
            options={
                'db_table': 'core_employees',
                'indexes': [models.Index(fields=['division', 'is_active'], name='idx_emp_div_active'), models.Index(fields=['full_name'], name='idx_emp_full_name')],
            },
        ),
    ]
