# Generated by Django 5.1.15 on 2026-06-07 16:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_useremployeebinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionHistoricalSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_slots', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_slots', to='core.division')),
            ],
            options={
                'db_table': 'core_division_historical_slots',
                'indexes': [models.Index(fields=['division', 'valid_from', 'valid_to'], name='idx_core_slots_timeline')],
            },
        ),
    ]
