# Generated by Django 5.1.15 on 2026-06-07 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_vacancy"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveFieldPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_code", models.CharField(max_length=100)),
                ("permission_code", models.CharField(max_length=100)),
                (
                    "mask_strategy",
                    models.CharField(
                        choices=[
                            ("FULL_HIDE", "Скрыть полностью"),
                            ("PARTIAL_MASK", "Частично маскировать"),
                            ("ALLOW", "Разрешить"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "core_sensitive_field_policies",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("field_code", "permission_code"),
                        name="unique_sensitive_policy",
                    )
                ],
            },
        ),
    ]
