# Generated by Django 5.1.15 on 2026-06-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_sensitivefieldpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watermark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("last_materialized_date", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_watermarks",
            },
        ),
    ]
