# Generated by Django 5.1.15 on 2026-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_watermark"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="divisionhistoricalslot",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeedivisionhistory",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeestaffingassignment",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sensitivefieldpolicy",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="staffingslot",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="useremployeebinding",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
