# Generated by Django 5.1.15 on 2026-08-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_opsemployeestatus_statusoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.IntegerField()),
                ('from_division_id', models.IntegerField()),
                ('to_division_id', models.IntegerField()),
                ('document_basis', models.TextField(blank=True, default='')),
                ('in_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondment_in', to='operations.opsemployeestatus')),
                ('out_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondment_out', to='operations.opsemployeestatus')),
            ],
            options={
                'db_table': 'ops_status_secondments',
                'indexes': [models.Index(fields=['employee_id', '-created_at'], name='idx_secondment_emp_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_division_id', models.F('to_division_id')), _negated=True), name='chk_secondment_divisions_differ'), models.CheckConstraint(condition=models.Q(('out_status', models.F('in_status')), _negated=True), name='chk_secondment_legs_differ')],
            },
        ),
    ]
