# Generated by Django 5.1.15 on 2026-08-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_secondment'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondment',
            name='return_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondment',
            name='return_confirmed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='secondment',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondment',
            name='return_requested_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='secondment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('return_requested_at__isnull', True), ('return_requested_by__isnull', True)), models.Q(('return_requested_at__isnull', False), ('return_requested_by__isnull', False), models.Q(('return_requested_by', ''), _negated=True)), _connector='OR'), name='chk_secondment_request_fact_complete'),
        ),
        migrations.AddConstraint(
            model_name='secondment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('return_confirmed_at__isnull', True), ('return_confirmed_by__isnull', True)), models.Q(('return_confirmed_at__isnull', False), ('return_confirmed_by__isnull', False), models.Q(('return_confirmed_by', ''), _negated=True)), _connector='OR'), name='chk_secondment_confirm_fact_complete'),
        ),
        migrations.AddConstraint(
            model_name='secondment',
            constraint=models.CheckConstraint(condition=models.Q(('return_confirmed_at__isnull', True), ('return_requested_at__isnull', False), _connector='OR'), name='chk_secondment_confirm_after_request'),
        ),
    ]
