# Generated by Django 5.1.15 on 2026-08-04 08:27

from django.db import migrations, models

# Журнал только дополняется. Запрет на уровне БД, а не только договорённости в
# сервисе: правка задним числом — единственное, что делает журнал
# бесполезным, и запретить её должен тот, кто хранит данные, а не тот, кто их
# пишет. Триггер строчный: TRUNCATE его не задевает, поэтому пересоздание
# тестовой базы и очистка стенда работают как обычно.
APPEND_ONLY_TRIGGER = """
CREATE OR REPLACE FUNCTION ops_audit_logs_append_only()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'ops_audit_logs дополняется только: % запрещён', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ops_audit_logs_append_only
BEFORE UPDATE OR DELETE ON ops_audit_logs
FOR EACH ROW EXECUTE FUNCTION ops_audit_logs_append_only();
"""

DROP_APPEND_ONLY_TRIGGER = """
DROP TRIGGER IF EXISTS trg_ops_audit_logs_append_only ON ops_audit_logs;
DROP FUNCTION IF EXISTS ops_audit_logs_append_only();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_secondment_return_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_user_id', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ops_audit_logs',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='idx_ops_audit_entity'), models.Index(fields=['actor_user_id', 'created_at'], name='idx_ops_audit_actor'), models.Index(fields=['action', 'created_at'], name='idx_ops_audit_action')],
            },
        ),
        migrations.RunSQL(
            sql=APPEND_ONLY_TRIGGER, reverse_sql=DROP_APPEND_ONLY_TRIGGER
        ),
    ]
