# Generated by Django 5.1.15 on 2026-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_opsauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsDailySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('division_id', models.IntegerField()),
                ('business_date', models.DateField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('event', models.CharField(choices=[('CONFIRMED_NO_CHANGES', 'Подтверждено без изменений'), ('CHANGED', 'Изменено'), ('AMENDED', 'Исправлено')], max_length=50)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField()),
                ('late', models.BooleanField(default=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('sanction', models.CharField(blank=True, default='', max_length=255)),
                ('triggered_by_status_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сдача дня',
                'verbose_name_plural': 'Сдачи дня',
                'db_table': 'ops_daily_submissions',
                'indexes': [models.Index(fields=['division_id', 'business_date', '-version'], name='idx_ops_submission_lookup')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('division_id', 'business_date'), name='unique_ops_submission_current'), models.UniqueConstraint(fields=('division_id', 'business_date', 'version'), name='unique_ops_submission_version'), models.CheckConstraint(condition=models.Q(('event__in', ['CONFIRMED_NO_CHANGES', 'CHANGED', 'AMENDED'])), name='chk_ops_submission_event'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='chk_ops_submission_version_min'), models.CheckConstraint(condition=models.Q(models.Q(('event', 'AMENDED'), _negated=True), models.Q(('reason__regex', '\\S'), ('sanction__regex', '\\S')), _connector='OR'), name='chk_ops_submission_amended_explained')],
            },
        ),
    ]
