# Generated by Django 5.1.15 on 2026-08-05 07:42

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models

# Содержимое массива «необходимых управлений» стережёт БД, а не Django: Q-язык
# не выражает предикатов по элементам массива, а дыра здесь дорогая. NULL или
# неположительный id в списке — это подразделение-ПРИЗРАК: сдачи у него не
# будет никогда, значит завтрашний день окажется заблокирован навсегда, и
# причину придётся искать в данных настройки, а не в сообщении об ошибке.
# Порядок конъюнктов несущий: `0 < ALL(...)` на массиве с NULL даёт NULL,
# который CHECK пропускает как «не ложь», поэтому NULL-гард идёт первым.
REQUIRED_IDS_CHECK = """
ALTER TABLE ops_submission_control_settings
    ADD CONSTRAINT chk_ops_control_settings_required_ids
    CHECK (
        array_position(required_division_ids, NULL) IS NULL
        AND 0 < ALL (required_division_ids)
    );
"""
DROP_REQUIRED_IDS_CHECK = """
ALTER TABLE ops_submission_control_settings
    DROP CONSTRAINT IF EXISTS chk_ops_control_settings_required_ids;
"""


def seed_settings(apps, schema_editor):
    """Строка настроек по умолчанию.

    Сеется миграцией, чтобы раздел читал НАСТРОЙКУ, а не «настройку, если её
    кто-то завёл»: пустая таблица заставила бы каждого читателя иметь свой
    запасной контрольный час, и они бы разошлись.
    """
    model = apps.get_model("operations", "OpsSubmissionControlSettings")
    model.objects.get_or_create(singleton_key=1)


def drop_settings(apps, schema_editor):
    model = apps.get_model("operations", "OpsSubmissionControlSettings")
    model.objects.filter(singleton_key=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_opsdailysubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsSubmissionControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('control_hour', models.TimeField(default=datetime.time(17, 0))),
                ('required_division_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Настройки контроля сдачи',
                'verbose_name_plural': 'Настройки контроля сдачи',
                'db_table': 'ops_submission_control_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_key', 1)), name='chk_ops_control_settings_singleton')],
            },
        ),
        migrations.RunSQL(REQUIRED_IDS_CHECK, DROP_REQUIRED_IDS_CHECK),
        migrations.RunPython(seed_settings, drop_settings),
    ]
