# Generated by Django 5.1.15 on 2026-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_opswatermark'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('SUBMISSION_LAGGING', 'Отставание по сдаче')], max_length=50)),
                ('business_date', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Уведомление раздела',
                'verbose_name_plural': 'Уведомления раздела',
                'db_table': 'ops_notifications',
                'indexes': [models.Index(fields=['recipient', '-created_at', 'id'], name='idx_ops_notif_recency')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'kind', 'business_date'), name='uq_ops_notif_recipient_kind_date'), models.CheckConstraint(condition=models.Q(('kind__in', ['SUBMISSION_LAGGING'])), name='chk_ops_notif_kind'), models.CheckConstraint(condition=models.Q(('recipient__regex', '^\\s*$'), _negated=True), name='chk_ops_notif_recipient')],
            },
        ),
    ]
