# Generated by Django 5.2.4 on 2026-08-06 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_opsdivisionnotifyrecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Вложение раздела',
                'verbose_name_plural': 'Вложения раздела',
                'db_table': 'ops_attachments',
                'indexes': [models.Index(fields=['sha256'], name='idx_ops_attachment_sha256')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='chk_ops_attachment_sha256'), models.CheckConstraint(condition=models.Q(('size__gte', 1)), name='chk_ops_attachment_size_min'), models.CheckConstraint(condition=models.Q(('original_name__regex', '\\S')), name='chk_ops_attachment_name'), models.CheckConstraint(condition=models.Q(('content_type__regex', '\\S')), name='chk_ops_attachment_content_type')],
            },
        ),
    ]
