# Generated by Django 5.1.15 on 2026-08-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_opssecurityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsDutyConflictPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('rest_after_duty_mode', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Политика конфликтов дежурств',
                'verbose_name_plural': 'Политика конфликтов дежурств',
                'db_table': 'ops_duty_conflict_policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('rest_after_duty_mode__in', ('HARD_BLOCK', 'SOFT_OVERRIDE'))), name='chk_ops_duty_policy_mode'), models.CheckConstraint(condition=models.Q(('version__regex', '\\S')), name='chk_ops_duty_policy_version')],
            },
        ),
        migrations.CreateModel(
            name='OpsDutyMonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(max_length=7, unique=True)),
                ('state_code', models.CharField(max_length=20)),
                ('revision', models.PositiveIntegerField()),
                ('last_validation', models.JSONField(null=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('history', models.JSONField()),
            ],
            options={
                'verbose_name': 'Месячный план дежурств',
                'verbose_name_plural': 'Месячные планы дежурств',
                'db_table': 'ops_duty_monthly_plans',
                'constraints': [models.CheckConstraint(condition=models.Q(('state_code__in', ('DRAFT', 'APPROVED'))), name='chk_ops_duty_plan_state'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='chk_ops_duty_plan_revision_floor'), models.CheckConstraint(condition=models.Q(('month__regex', '^\\d{4}-\\d{2}$')), name='chk_ops_duty_plan_month_format')],
            },
        ),
        migrations.CreateModel(
            name='OpsDutyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('business_date', models.DateField()),
                ('duty_type_code', models.CharField(max_length=50)),
                ('target', models.JSONField()),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=50, null=True)),
                ('state_code', models.CharField(max_length=20)),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('actual_start', models.DateTimeField(null=True)),
                ('actual_end', models.DateTimeField(null=True)),
                ('passport_binding', models.JSONField(null=True)),
                ('note', models.TextField(null=True)),
                ('cancellation', models.JSONField(null=True)),
                ('override_reason', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Смена дежурства',
                'verbose_name_plural': 'Смены дежурств',
                'db_table': 'ops_duty_shifts',
                'ordering': ['business_date', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('state_code__in', ('PLANNED', 'ACKNOWLEDGED', 'ACTIVE', 'COMPLETED', 'CANCELLED'))), name='chk_ops_duty_shift_state'), models.CheckConstraint(condition=models.Q(('duty_type_code__regex', '\\S')), name='chk_ops_duty_shift_type_code')],
            },
        ),
        migrations.CreateModel(
            name='OpsDutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('duty_type_code', models.CharField(max_length=50, unique=True)),
                ('safe_label', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=20)),
                ('default_duration_minutes', models.PositiveIntegerField()),
                ('requires_senior', models.BooleanField()),
                ('rest_after_minutes', models.PositiveIntegerField()),
                ('requires_current_passport', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Вид дежурства',
                'verbose_name_plural': 'Виды дежурств',
                'db_table': 'ops_duty_types',
                'ordering': ['duty_type_code', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_type__in', ('OWN_OBJECT', 'PROTECTED_OBJECT'))), name='chk_ops_duty_type_target'), models.CheckConstraint(condition=models.Q(('duty_type_code__regex', '\\S')), name='chk_ops_duty_type_code')],
            },
        ),
    ]
