# Generated by Django 5.1.15 on 2026-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_opsdutyconflictpolicy_opsdutymonthlyplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsCombatDutyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('business_date', models.DateField()),
                ('duty_type_code', models.CharField(max_length=50)),
                ('route_set', models.JSONField()),
                ('submission', models.JSONField(null=True)),
                ('required_employees', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Смена боевой группы',
                'verbose_name_plural': 'Смены боевых групп',
                'db_table': 'ops_combat_duty_shifts',
                'ordering': ['business_date', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duty_type_code__regex', '\\S')), name='chk_ops_combat_shift_type_code')],
            },
        ),
        migrations.CreateModel(
            name='OpsCombatDutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('duty_type_code', models.CharField(max_length=50, unique=True)),
                ('safe_label', models.CharField(max_length=255)),
                ('supports_multiple_routes', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Вид дежурства боевой группы',
                'verbose_name_plural': 'Виды дежурств боевых групп',
                'db_table': 'ops_combat_duty_types',
                'ordering': ['duty_type_code', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duty_type_code__regex', '\\S')), name='chk_ops_combat_type_code')],
            },
        ),
        migrations.CreateModel(
            name='OpsCombatRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('route_code', models.CharField(max_length=50, unique=True)),
                ('safe_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Трасса',
                'verbose_name_plural': 'Трассы',
                'db_table': 'ops_combat_routes',
                'ordering': ['route_code', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('route_code__regex', '\\S')), name='chk_ops_combat_route_code')],
            },
        ),
    ]
