# Generated by Django 5.1.15 on 2026-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_opscombatdutyshift_opscombatdutytype_opscombatroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsSettingChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('setting_code', models.CharField(max_length=100)),
                ('section_code', models.CharField(max_length=50)),
                ('safe_label', models.CharField(max_length=255)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('actor_user_id', models.CharField(max_length=255)),
                ('policy_version_after', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Изменение настройки',
                'verbose_name_plural': 'Изменения настроек',
                'db_table': 'ops_setting_change_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OpsDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dictionary_code', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField()),
                ('group_code', models.CharField(max_length=100, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Значение справочника ОМ',
                'verbose_name_plural': 'Значения справочников ОМ',
                'db_table': 'ops_dictionary_entries',
                'ordering': ['dictionary_code', 'code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('dictionary_code', 'code'), name='uniq_ops_dictionary_entry_code'), models.CheckConstraint(condition=models.Q(('dictionary_code__in', ('RETURN_REASONS', 'POST_REQUIREMENTS', 'SEASONAL_CORRECTIONS', 'JOURNAL_ENTRY_TYPES', 'POST_REQUIREMENT_GROUPS'))), name='chk_ops_dictionary_code'), models.CheckConstraint(condition=models.Q(('code__regex', '\\S')), name='chk_ops_dictionary_entry_value_code')],
            },
        ),
        migrations.CreateModel(
            name='OpsPolicySectionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('section_code', models.CharField(max_length=50, unique=True)),
                ('version', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Версия раздела настроек',
                'verbose_name_plural': 'Версии разделов настроек',
                'db_table': 'ops_policy_section_versions',
                'constraints': [models.CheckConstraint(condition=models.Q(('section_code__in', ('CONFLICT_RULES', 'PASSPORT_FRESHNESS', 'RATING_POLICY', 'ANALYTICS_LIMITS', 'LOAD_POLICY', 'ATTENTION_POLICY', 'REPORT_LIMITS'))), name='chk_ops_section_version_code'), models.CheckConstraint(condition=models.Q(('version__regex', '\\S')), name='chk_ops_section_version_value')],
            },
        ),
        migrations.CreateModel(
            name='OpsPolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('setting_code', models.CharField(max_length=100, unique=True)),
                ('section_code', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=20)),
                ('value_type', models.CharField(max_length=20)),
                ('safe_label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value', models.JSONField()),
                ('min_value', models.IntegerField(null=True)),
                ('max_value', models.IntegerField(null=True)),
                ('options', models.JSONField(null=True)),
                ('editable', models.BooleanField()),
                ('locked_reason', models.TextField(null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('value_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Настройка раздела ОМ',
                'verbose_name_plural': 'Настройки раздела ОМ',
                'db_table': 'ops_policy_settings',
                'ordering': ['section_code', 'setting_code', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('section_code__in', ('CONFLICT_RULES', 'PASSPORT_FRESHNESS', 'RATING_POLICY', 'ANALYTICS_LIMITS', 'LOAD_POLICY', 'ATTENTION_POLICY', 'REPORT_LIMITS'))), name='chk_ops_setting_section'), models.CheckConstraint(condition=models.Q(('kind__in', ('NUMBER', 'CHOICE'))), name='chk_ops_setting_kind'), models.CheckConstraint(condition=models.Q(('setting_code__regex', '\\S')), name='chk_ops_setting_code')],
            },
        ),
    ]
