# Generated by Django 5.1.15 on 2026-08-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_opsservicereporttype_opsservicereportartifact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsFeedbackRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('version', models.CharField(max_length=100)),
                ('types', models.JSONField()),
                ('priorities', models.JSONField()),
                ('statuses', models.JSONField()),
                ('modules', models.JSONField()),
                ('status_transitions', models.JSONField()),
                ('terminal_statuses', models.JSONField()),
            ],
            options={
                'verbose_name': 'Справочник обратной связи',
                'verbose_name_plural': 'Справочник обратной связи',
                'db_table': 'ops_feedback_registry',
            },
        ),
        migrations.CreateModel(
            name='OpsFeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('type_code', models.CharField(max_length=30)),
                ('priority_code', models.CharField(max_length=20)),
                ('status_code', models.CharField(max_length=20)),
                ('module_code', models.CharField(max_length=50)),
                ('expected_result', models.TextField(null=True)),
                ('reproduction_steps', models.TextField(null=True)),
                ('attachments', models.JSONField(default=list)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('confidential', models.BooleanField()),
                ('related_route', models.CharField(max_length=255, null=True)),
                ('technical_info', models.JSONField(null=True)),
                ('working_priority_code', models.CharField(max_length=20, null=True)),
                ('assignee_user_id', models.CharField(max_length=255, null=True)),
                ('assignee_label', models.CharField(max_length=255, null=True)),
                ('author_user_id', models.CharField(max_length=255)),
                ('author_label', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('duplicate_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='operations.opsfeedbackrequest')),
            ],
            options={
                'verbose_name': 'Обращение обратной связи',
                'verbose_name_plural': 'Обращения обратной связи',
                'db_table': 'ops_feedback_requests',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpsFeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('kind', models.CharField(max_length=40)),
                ('actor_user_id', models.CharField(max_length=255)),
                ('actor_label', models.CharField(max_length=255)),
                ('at', models.DateTimeField()),
                ('field_code', models.CharField(max_length=50, null=True)),
                ('old_value', models.TextField(null=True)),
                ('new_value', models.TextField(null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='operations.opsfeedbackrequest')),
            ],
            options={
                'verbose_name': 'Событие обращения',
                'verbose_name_plural': 'События обращений',
                'db_table': 'ops_feedback_events',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpsFeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('kind', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('author_user_id', models.CharField(max_length=255)),
                ('author_label', models.CharField(max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.opsfeedbackrequest')),
            ],
            options={
                'verbose_name': 'Комментарий обращения',
                'verbose_name_plural': 'Комментарии обращений',
                'db_table': 'ops_feedback_comments',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
