# Generated by Django 5.1.15 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_opssecurityevent_approval_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityevent',
            name='business_date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
