# Generated by Django 5.1.15 on 2026-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_opsgvosummarypatch_opsprotectedperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsLegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('kind', models.CharField(choices=[('LAW', 'Закон'), ('ORDER', 'Приказ'), ('REGULATION', 'Регламент'), ('INSTRUCTION', 'Инструкция')], max_length=20)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('revision', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('IN_FORCE', 'Действует'), ('UNDER_REVIEW', 'На пересмотре')], max_length=20)),
                ('pages', models.PositiveIntegerField()),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'code', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ('LAW', 'ORDER', 'REGULATION', 'INSTRUCTION'))), name='chk_ops_legal_document_kind'), models.CheckConstraint(condition=models.Q(('status__in', ('IN_FORCE', 'UNDER_REVIEW'))), name='chk_ops_legal_document_status')],
            },
        ),
    ]
