# Generated by Django 5.1.15 on 2026-08-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0036_opssecurityevent_recon_force_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsVisitObjectDeputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.PositiveIntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('can_edit_placement', models.BooleanField(default=True)),
                ('assigned_by', models.CharField(max_length=255)),
                ('visit_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputies', to='operations.opssecurityeventvisitobject')),
            ],
            options={
                'verbose_name': 'Замещающий на объекте посещения',
                'verbose_name_plural': 'Замещающие на объектах посещения',
                'db_table': 'ops_visit_object_deputies',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('visit_object', 'employee_id'), name='uniq_ops_visit_object_deputy'), models.CheckConstraint(condition=models.Q(('employee_name__regex', '\\S')), name='chk_ops_visit_object_deputy_name')],
            },
        ),
    ]
