# Generated by Django 5.1.15 on 2026-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0037_opsvisitobjectdeputy'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityeventvisitobject',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opssecurityeventvisitobject',
            name='visit_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
