# Generated by Django 5.1.15 on 2026-08-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0039_backfill_visit_days_from_gvo_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityeventvisitobject',
            name='chief_employee_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opssecurityeventvisitobject',
            name='chief_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
