# Generated by Django 5.1.15 on 2026-08-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0049_passport_state_backfill'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='opsratingauditentry',
            constraint=models.CheckConstraint(condition=models.Q(('event_code__in', ('EVALUATION_SUBMITTED', 'EVALUATION_SCORE_CHANGED_FROM_INITIAL', 'EVALUATION_LOW_SCORE_WITHOUT_COMMENT', 'EVALUATION_CORRECTED', 'EVALUATION_CORRECTION_REJECTED', 'EVALUATION_ACCESS_DENIED', 'RATING_EXPORT_REQUESTED', 'RATING_EXPORT_DOWNLOADED', 'RATING_EXPORT_REJECTED'))), name='chk_ops_rating_audit_event_code'),
        ),
    ]
