# Generated by Django 5.1.15 on 2026-08-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0051_opssecurityevent_protected_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(max_length=200)),
                ('body_class', models.CharField(blank=True, max_length=100)),
                ('production_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plate', models.CharField(max_length=32)),
                ('armor_class', models.CharField(blank=True, max_length=32)),
                ('deployment', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'транспорт ГОН',
                'verbose_name_plural': 'Транспорт ГОН',
                'db_table': 'ops_vehicles',
                'ordering': ['brand', 'plate', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('plate',), name='uniq_ops_vehicle_active_plate')],
            },
        ),
    ]
