# Generated by Django 5.1.15 on 2026-08-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0057_event_assignment_group_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opsnotification',
            name='chk_ops_notif_kind',
        ),
        migrations.AlterField(
            model_name='opsnotification',
            name='kind',
            field=models.CharField(choices=[('SUBMISSION_LAGGING', 'Отставание по сдаче'), ('EVENT_ACKNOWLEDGEMENT', 'Заступление на ОМ')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='opsnotification',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['SUBMISSION_LAGGING', 'EVENT_ACKNOWLEDGEMENT'])), name='chk_ops_notif_kind'),
        ),
    ]
