"""Виды участия в ОМ и роли внутри группы — в закрытый список справочников.

Заказчик (Plane №274): «выбор Физнаряд и разные специфические группы, эти
группы имеют разные статусы (например: группа Досмотра, внутри досмотрщик,
кинолог)».

Список кодов справочников закрыт ПРОВЕРКОЙ В БАЗЕ, а не только питоновским
кортежем: без этой миграции новые коды отбиваются `IntegrityError` на вставке,
и заметно это только пробой. Данные миграция не трогает — она расширяет
разрешённый список.
"""
# Generated by Django 5.1.15 on 2026-08-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0060_roles_decided_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opsdictionaryentry',
            name='chk_ops_dictionary_code',
        ),
        migrations.AddConstraint(
            model_name='opsdictionaryentry',
            constraint=models.CheckConstraint(condition=models.Q(('dictionary_code__in', ('RETURN_REASONS', 'POST_REQUIREMENTS', 'SEASONAL_CORRECTIONS', 'JOURNAL_ENTRY_TYPES', 'POST_REQUIREMENT_GROUPS', 'PLACEMENT_ROLES', 'EVENT_PARTICIPATION_KINDS', 'EVENT_GROUP_ROLES'))), name='chk_ops_dictionary_code'),
        ),
    ]
