"""Участие статуса в мероприятии + БЭКФИЛЛ существующих строк (Plane №274).

Новая сущность не должна быть пустой у уже заведённого: сегодня выделение
штабом пишет статус с `source_ref = "security-event:<id>"`, и эта связь —
ровно то, что теперь живёт строкой участия. Без переноса департаментский экран
(Ш-5) увидел бы пустоту там, где люди выделены месяцами.

Вид участия выводится ИЗ КОДА СТАТУСА, а не угадывается:
`EVENT_ASSIGNMENT` — физический наряд, `EVENT_ASSIGNMENT_GROUP` — группа.
У группы роль не проставляется: в старых данных её нет вовсе, и придумать её
задним числом значило бы записать людей в досмотрщики наугад.

Обратный перенос стирает только перенесённое (строки участия) — сами статусы
не трогаются.
"""
# Generated by Django 5.1.15 on 2026-08-28 14:32

import django.db.models.deletion
from django.db import migrations, models


def _backfill(apps, schema_editor):
    Status = apps.get_model("operations", "OpsEmployeeStatus")
    Participation = apps.get_model("operations", "OpsStatusParticipation")
    kind_of = {
        "EVENT_ASSIGNMENT": "PHYSICAL_SQUAD",
        "EVENT_ASSIGNMENT_GROUP": "SCREENING_GROUP",
    }
    rows = []
    for status in Status.objects.filter(
        status_type_code__in=kind_of, source_ref__startswith="security-event:"
    ).only("id", "status_type_code", "source_ref"):
        raw = (status.source_ref or "").split(":", 1)[-1].strip()
        if not raw.isdigit():
            # Ссылка нечисловая — пропускаем молча НЕЛЬЗЯ, но и падать на
            # миграции из-за одной кривой строки тоже нельзя: такие строки
            # просто не переносятся, а сам статус остаётся жить.
            continue
        rows.append(
            Participation(
                status_id=status.id,
                event_id=int(raw),
                kind_code=kind_of[status.status_type_code],
                role_code="",
            )
        )
    Participation.objects.bulk_create(rows, ignore_conflicts=True)


def _unbackfill(apps, schema_editor):
    # Обратный перенос стирает только строки участия; статусы не трогаются.
    apps.get_model("operations", "OpsStatusParticipation").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0061_event_participation_dictionaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsStatusParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('event_id', models.IntegerField()),
                ('kind_code', models.CharField(max_length=100)),
                ('role_code', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='operations.opsemployeestatus')),
            ],
            options={
                'verbose_name': 'Участие в мероприятии',
                'verbose_name_plural': 'Участия в мероприятиях',
                'db_table': 'ops_status_participations',
                'ordering': ['status_id', 'event_id', 'id'],
                'indexes': [models.Index(fields=['event_id'], name='idx_participation_event')],
                'constraints': [models.UniqueConstraint(fields=('status', 'event_id'), name='uniq_status_participation_event')],
            },
        ),
            migrations.RunPython(_backfill, _unbackfill),
    ]
