# Generated by Django 5.1.15 on 2026-08-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0065_allocation_due_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opsdictionaryentry',
            name='chk_ops_dictionary_code',
        ),
        migrations.AddConstraint(
            model_name='opsdictionaryentry',
            constraint=models.CheckConstraint(condition=models.Q(('dictionary_code__in', ('RETURN_REASONS', 'POST_REQUIREMENTS', 'SEASONAL_CORRECTIONS', 'JOURNAL_ENTRY_TYPES', 'POST_REQUIREMENT_GROUPS', 'PLACEMENT_ROLES', 'EVENT_PARTICIPATION_KINDS', 'EVENT_GROUP_ROLES', 'PLACEMENT_SECTIONS'))), name='chk_ops_dictionary_code'),
        ),
    ]
