"""Plane №398 (`[СОГ-04]`): версии документа «Расстановка сил» — своей таблицей.

Требование: «После согласования версия замораживается; любое изменение = новая
версия → повторное согласование. Все версии хранятся, видны в „Истории
версий“; отменённые помечены». До этого у объекта посещения был только НОМЕР
текущей версии (`document_version`, №396/№411): состав, под которым
подписывались, жил строкой-подписью и терялся при следующей отправке.

БЭКФИЛЛА НЕТ — НАМЕРЕННО. Восстановить прошлые версии нечем: снимки состава
не хранились, а придуманная история хуже пустой. Текущая версия каждого
объекта с `document_version > 0` заводится в таблице ПЕРВЫМ ЖЕ переходом
сервиса (завершение расстановки / отправка / решение): сервис при записи
версии сверяется с таблицей и, не найдя строку с текущим номером, создаёт её
из живого состава. Так история начинается с честной точки «с этого момента»,
а не с реконструкции.
"""

# Generated by Django 5.1.15 on 2026-09-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0072_remove_unused_event_stage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsPlacementDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'На согласовании'), ('APPROVED', 'Согласовано'), ('RETURNED', 'Возвращено')], default='DRAFT', max_length=20)),
                ('signature', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('visit_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='operations.opssecurityeventvisitobject')),
            ],
            options={
                'verbose_name': 'Версия документа «Расстановка сил»',
                'verbose_name_plural': 'Версии документа «Расстановка сил»',
                'db_table': 'ops_placement_document_versions',
                'ordering': ['visit_object_id', 'number'],
                'constraints': [models.UniqueConstraint(fields=('visit_object', 'number'), name='uniq_ops_placement_document_version'), models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='chk_ops_placement_document_version_number'), models.CheckConstraint(condition=models.Q(('status__in', ('DRAFT', 'SUBMITTED', 'APPROVED', 'RETURNED'))), name='chk_ops_placement_document_version_status')],
            },
        ),
    ]
