"""Справочники «страна → город» и код `OL-N` охраняемого лица (Plane №417).

Код бэкфиллится всем существующим лицам по их идентификатору — тем же
правилом, каким модель выдаёт его новым: `OL-<id>`. Поле допускает NULL
(у Postgres NULL не нарушает unique): строка, вставленная мимо `save()`
(`bulk_create`), кода не получает, но он у неё выводим — см.
`OpsProtectedPerson.display_code`.

Сид стран и городов — минимальный рабочий набор (Казахстан с областными
центрами и соседи/частые направления визитов): новая сущность не должна быть
пустой у уже работающего раздела. Сид идемпотентен по ISO-коду и имени;
откат сид не трогает (администратор мог дописать свои строки).
"""
# Generated by Django 5.1.15 on 2026-09-03 19:13

import django.db.models.deletion
from django.db import migrations, models

SEED = {
    ("KZ", "Казахстан"): [
        "Астана", "Алматы", "Шымкент", "Караганда", "Актобе", "Тараз",
        "Павлодар", "Усть-Каменогорск", "Семей", "Атырау", "Костанай",
        "Кызылорда", "Уральск", "Петропавловск", "Актау", "Туркестан",
        "Кокшетау", "Талдыкорган", "Экибастуз", "Жезказган",
    ],
    ("RU", "Россия"): ["Москва", "Санкт-Петербург", "Казань", "Сочи"],
    ("UZ", "Узбекистан"): ["Ташкент", "Самарканд"],
    ("KG", "Кыргызстан"): ["Бишкек"],
    ("TJ", "Таджикистан"): ["Душанбе"],
    ("TM", "Туркменистан"): ["Ашхабад"],
    ("AZ", "Азербайджан"): ["Баку"],
    ("TR", "Турция"): ["Анкара", "Стамбул"],
    ("CN", "Китай"): ["Пекин", "Шанхай", "Урумчи"],
    ("AE", "ОАЭ"): ["Абу-Даби", "Дубай"],
    ("US", "США"): ["Вашингтон", "Нью-Йорк"],
    ("FR", "Франция"): ["Париж"],
    ("DE", "Германия"): ["Берлин"],
    ("GB", "Великобритания"): ["Лондон"],
}


def backfill_codes(apps, schema_editor):
    Person = apps.get_model("operations", "OpsProtectedPerson")
    for person in Person.objects.filter(code__isnull=True).only("id"):
        Person.objects.filter(pk=person.pk).update(code=f"OL-{person.pk}")


def seed_geo(apps, schema_editor):
    Country = apps.get_model("operations", "OpsCountry")
    City = apps.get_model("operations", "OpsCity")
    for (code, name), cities in SEED.items():
        country, _ = Country.objects.get_or_create(code=code, defaults={"name": name})
        for city in cities:
            City.objects.get_or_create(country=country, name=city)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0077_visit_object_closing_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsprotectedperson',
            name='code',
            field=models.CharField(editable=False, max_length=24, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OpsCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z]{2}$')), name='chk_ops_country_code_iso2')],
            },
        ),
        migrations.CreateModel(
            name='OpsCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='operations.opscountry')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['country__name', 'name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('country', 'name'), name='uq_ops_city_country_name')],
            },
        ),
        migrations.RunPython(backfill_codes, migrations.RunPython.noop),
        migrations.RunPython(seed_geo, migrations.RunPython.noop),
    ]
