"""Визит иностранного ОЛ — своя сущность (Plane №435, `[МД-05]`, Ш-19).

Бэкфилл: каждому мероприятию `kind=FOREIGN` заводится визит; сохранённые
ручные правки сводки (`OpsGvoSummaryPatch`) копируются в `data` — новая
сущность не должна быть пустой у уже заведённых визитов. Патч не
удаляется: его читают, пока страницу не переведут (Ш-20). Внутренним ОМ
визит не заводится вовсе.
"""
# Generated by Django 5.1.15 on 2026-09-03 23:32

import django.db.models.deletion
from django.db import migrations, models


def backfill_visits(apps, schema_editor):
    Event = apps.get_model("operations", "OpsSecurityEvent")
    Patch = apps.get_model("operations", "OpsGvoSummaryPatch")
    Visit = apps.get_model("operations", "OpsForeignVisit")
    patches = {p.event_id: p.patch for p in Patch.objects.all()}
    for event in Event.objects.filter(kind="FOREIGN"):
        data = patches.get(event.pk) or {}
        Visit.objects.get_or_create(
            event=event,
            defaults={
                "protected_person_id": event.protected_person_id,
                "data": data,
                "status": "READY" if data else "DRAFT",
            },
        )



class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0085_notification_kind_forces_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsForeignVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('READY', 'Заполнен'), ('APPROVED', 'Утверждён')], default='DRAFT', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('unspecified', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_visit', to='operations.opssecurityevent')),
                ('protected_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.opsprotectedperson')),
            ],
            options={
                'verbose_name': 'Визит иностранного ОЛ',
                'verbose_name_plural': 'Визиты иностранных ОЛ',
                'ordering': ['event_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('DRAFT', 'READY', 'APPROVED'))), name='chk_ops_foreign_visit_status')],
            },
        ),
        migrations.RunPython(backfill_visits, migrations.RunPython.noop),
    ]
