# Generated by Django 5.1.15 on 2026-09-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0088_recon_checklist_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opsdepartmentrequest',
            options={'ordering': ['event_id', 'allocation_key', 'sequence'], 'verbose_name': 'Запрос департаменту', 'verbose_name_plural': 'Запросы департаментам'},
        ),
        migrations.AlterModelOptions(
            name='opsforcerequest',
            options={'ordering': ['event_id', 'source_key', 'sequence'], 'verbose_name': 'Заявка на сбор сил', 'verbose_name_plural': 'Заявки на сбор сил'},
        ),
        migrations.AlterModelOptions(
            name='opsforcerequestmember',
            options={'ordering': ['event_id', 'allocation_key', 'added_at', 'pk'], 'verbose_name': 'Сотрудник в составе по запросу', 'verbose_name_plural': 'Состав по запросам'},
        ),
        migrations.AlterModelOptions(
            name='opsunitrequest',
            options={'ordering': ['event_id', 'directorate_key', 'sequence'], 'verbose_name': 'Запрос управлению', 'verbose_name_plural': 'Запросы управлениям'},
        ),
    ]
