"""`dedupe_key` у уведомления раздела: «одно на день» перестаёт быть законом
для ВСЕХ видов (Plane №677).

Ключ (получатель, вид, деловая дата) заведён ради ДОГОНА — он по построению
переспрашивает пройденные дни. Но часть фактов за день случается много раз:
три департамента отвечают штабу на запрос сил (`FORCES_RESPONSE`,
`[СБС-12]`) — это три разных ответа, а не три пересказа одного, и под общим
ключом второй и третий пропадали молча.

СУЩЕСТВУЮЩИЕ СТРОКИ НЕ МЕНЯЮТ ПОВЕДЕНИЯ: колонка добавляется со значением
`''` (пустая строка), и ограничение с ней сходится к прежнему
(получатель, вид, дата, `''`). Это и есть бэкфилл — отдельным шагом он не
нужен. `NULL` в колонке появляется только у тех вызовов, которые просят его
явно (`notify(..., dedupe_key=None)`), и Postgres считает такие строки
различными — потому они и не схлопываются.
"""

# Generated by Django 5.1.15 on 2026-09-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0092_repair_event_assignment_merge'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opsnotification',
            name='uq_ops_notif_recipient_kind_date',
        ),
        migrations.AddField(
            model_name='opsnotification',
            name='dedupe_key',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='opsnotification',
            constraint=models.UniqueConstraint(fields=('recipient', 'kind', 'business_date', 'dedupe_key'), name='uq_ops_notif_recipient_kind_date_key'),
        ),
    ]
