# Generated by Django 5.1.15 on 2026-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0106_protected_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsprotectedperson',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='opsprotectedperson',
            name='facts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opsprotectedperson',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
