# Generated by Django 5.1.15 on 2026-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0110_forces_officer_status_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsdailysubmission',
            name='incomplete_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opsdailysubmission',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsdailysubmission',
            name='sent_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='opsdailysubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', True), ('sent_by', '')), models.Q(('sent_at__isnull', False), ('sent_by__regex', '\\S')), _connector='OR'), name='chk_ops_submission_sent_together'),
        ),
    ]
