# Generated by Django 5.1.15 on 2026-09-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    # Зависимость от 0111 (ещё не закоммичен на момент этой миграции —
    # соседняя параллельная сессия ведёт его локально, согласовано напрямую,
    # см. Plane SJ-1049): зависимость от 0110 давала ДВА листа графа миграций
    # и `migrate`/`makemigrations --check` отказывались работать вовсе, пока
    # 0111 лежит на диске. 0111 физически присутствует и не переименован —
    # если это изменится до его коммита, дождаться нового имени и поправить
    # здесь.
    dependencies = [
        ('operations', '0111_department_summary_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityeventvisitobject',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opssecurityobject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='security-objects/photos/'),
        ),
    ]
