# Generated by Django 5.1.15 on 2026-09-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    # №982 занимает 0112 и добавляет состояние рекогносцировки объекта.
    # Фото объекта и описание посещения идут следующим последовательным
    # узлом, чтобы у приложения operations оставался один лист графа.
    dependencies = [
        ('operations', '0112_visit_object_recon_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='opssecurityeventvisitobject',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opssecurityobject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='security-objects/photos/'),
        ),
    ]
