# Generated by Django 5.1.15 on 2026-09-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0116_force_campaign_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsE2EFixtureDateCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('next_offset', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Курсор дат e2e-фикстур',
                'verbose_name_plural': 'Курсоры дат e2e-фикстур',
                'db_table': 'ops_e2e_fixture_date_cursor',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_key', 1)), name='chk_ops_e2e_fixture_date_cursor_singleton')],
            },
        ),
    ]
