# Generated by Django 5.1.15 on 2026-09-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0117_opse2efixturedatecursor'),
        ('operations', '0117_protected_person_photo_private_storage'),
        ('operations', '0118_dictionary_entry_owner_division'),
        ('operations', '0121_report_artifact_series_uniqueness'),
    ]

    operations = [
    ]
