# Generated by Django 5.1.15 on 2026-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at", "id"],
                name="ix_notif_recipient_recency",
            ),
        ),
    ]
